/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 /Users/luis/GithubProjects/CaveGame/my-three-app/public/assets/models/caves/cave.glb --output src/components/Caves/caveModel.tsx --types --bones --public-path /assets/models/caves 
Author: Valsev (https://sketchfab.com/Valsev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cave-43b086dfaed343e1ba5b23416c260325
Title: Cave
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'Camera|CameraAction'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Cube001_Material001_0: THREE.Mesh
    Cube001_Material002_0: THREE.Mesh
    Cube002_Material001_0: THREE.Mesh
    Cube002_Material002_0: THREE.Mesh
    Cube003_Material001_0: THREE.Mesh
    Cube003_Material002_0: THREE.Mesh
    Cube011_Material_0: THREE.Mesh
    Cube012_Material_0: THREE.Mesh
    Cube013_Material_0: THREE.Mesh
    Cube014_Material_0: THREE.Mesh
    Cube015_Material_0: THREE.Mesh
    Cube016_Material_0: THREE.Mesh
    Cube017_Material_0: THREE.Mesh
    Cube018_Material_0: THREE.Mesh
    Cube019_Material_0: THREE.Mesh
    Cube020_Material_0: THREE.Mesh
    Cube021_Material_0: THREE.Mesh
    Cube022_Material_0: THREE.Mesh
    Cube023_Material_0: THREE.Mesh
    Cube024_Material_0: THREE.Mesh
    Cube025_Material_0: THREE.Mesh
    Cube026_Material_0: THREE.Mesh
    Cube027_Material_0: THREE.Mesh
    Cube028_Material_0: THREE.Mesh
    Cube029_Material_0: THREE.Mesh
    Cube030_Material_0: THREE.Mesh
    Cube031_Material_0: THREE.Mesh
    Cube032_Material_0: THREE.Mesh
    Cube033_Material_0: THREE.Mesh
    Cube034_Material_0: THREE.Mesh
    Cube035_Material_0: THREE.Mesh
    Cube036_Material_0: THREE.Mesh
    Cube037_Material_0: THREE.Mesh
    Cube038_Material_0: THREE.Mesh
    Cube039_Material_0: THREE.Mesh
    Cube040_Material_0: THREE.Mesh
    Cube041_Material_0: THREE.Mesh
    Cube042_Material_0: THREE.Mesh
    Cube043_Material_0: THREE.Mesh
    Cube044_Material_0: THREE.Mesh
    Cube045_Material_0: THREE.Mesh
    Cube046_Material_0: THREE.Mesh
    Cube047_Material_0: THREE.Mesh
    Cube048_Material_0: THREE.Mesh
    Cube049_Material_0: THREE.Mesh
    Cube050_Material_0: THREE.Mesh
    Cube051_Material_0: THREE.Mesh
    Cube052_Material_0: THREE.Mesh
    Cube053_Material_0: THREE.Mesh
    Cube054_Material_0: THREE.Mesh
    Cube055_Material_0: THREE.Mesh
    Cube056_Material_0: THREE.Mesh
    Cube057_Material_0: THREE.Mesh
    Cube058_Material001_0: THREE.Mesh
    Cube058_Material002_0: THREE.Mesh
    Cube059_Material001_0: THREE.Mesh
    Cube059_Material002_0: THREE.Mesh
    Cube060_Material001_0: THREE.Mesh
    Cube060_Material002_0: THREE.Mesh
    Cube061_Material001_0: THREE.Mesh
    Cube061_Material002_0: THREE.Mesh
    Cube063_Material002_0: THREE.Mesh
    Cube062_Material002_0: THREE.Mesh
    Cube064_Material002_0: THREE.Mesh
    Cube065_Material001_0: THREE.Mesh
    Cube065_Material002_0: THREE.Mesh
    Cube066_Material001_0: THREE.Mesh
    Cube066_Material002_0: THREE.Mesh
    Cube067_Material001_0: THREE.Mesh
    Cube067_Material002_0: THREE.Mesh
    Cube076_Material_0: THREE.Mesh
    Cube077_Material_0: THREE.Mesh
    Cube078_Material_0: THREE.Mesh
    Cube079_Material_0: THREE.Mesh
    Cube080_Material_0: THREE.Mesh
    Cube081_Material_0: THREE.Mesh
    Cube082_Material_0: THREE.Mesh
    Cube083_Material_0: THREE.Mesh
    Cube084_Material_0: THREE.Mesh
    Cube085_Material_0: THREE.Mesh
    Cube086_Material_0: THREE.Mesh
    Cube087_Material_0: THREE.Mesh
    Cube088_Material_0: THREE.Mesh
    Cube089_Material_0: THREE.Mesh
    Cube090_Material_0: THREE.Mesh
    Cube091_Material_0: THREE.Mesh
    Cube092_Material_0: THREE.Mesh
    Cube093_Material_0: THREE.Mesh
    Cube094_Material_0: THREE.Mesh
    Cube095_Material_0: THREE.Mesh
    Cube096_Material_0: THREE.Mesh
    Cube097_Material_0: THREE.Mesh
    Cube098_Material_0: THREE.Mesh
    Cube099_Material_0: THREE.Mesh
    Cube100_Material_0: THREE.Mesh
    Cube101_Material_0: THREE.Mesh
    Cube102_Material_0: THREE.Mesh
    Cube103_Material_0: THREE.Mesh
    Cube104_Material_0: THREE.Mesh
    Cube105_Material_0: THREE.Mesh
    Cube106_Material_0: THREE.Mesh
    Cube107_Material_0: THREE.Mesh
    Cube108_Material_0: THREE.Mesh
    Cube109_Material_0: THREE.Mesh
    Cube110_Material_0: THREE.Mesh
    Cube111_Material_0: THREE.Mesh
    Cube112_Material_0: THREE.Mesh
    Cube113_Material_0: THREE.Mesh
    Cube114_Material_0: THREE.Mesh
    Cube115_Material_0: THREE.Mesh
    Cube116__0: THREE.Mesh
    Cube117_Material_0: THREE.Mesh
    Cube118_Material_0: THREE.Mesh
    Cube119__0: THREE.Mesh
    Cube120_Material_0: THREE.Mesh
    Cube121_Material_0: THREE.Mesh
    Cube122_Material_0: THREE.Mesh
    Cube123_Material001_0: THREE.Mesh
    Cube123_Material002_0: THREE.Mesh
    Cube124_Material001_0: THREE.Mesh
    Cube124_Material002_0: THREE.Mesh
    Cube125_Material001_0: THREE.Mesh
    Cube125_Material002_0: THREE.Mesh
    Cube126_Material001_0: THREE.Mesh
    Cube126_Material002_0: THREE.Mesh
    Cube127_Material002_0: THREE.Mesh
    Cube128_Material002_0: THREE.Mesh
    Cube129_Material002_0: THREE.Mesh
    Cube006_Material001_0: THREE.Mesh
    Cube006_Material002_0: THREE.Mesh
    Cube068_Material001_0: THREE.Mesh
    Cube068_Material002_0: THREE.Mesh
    Cube070_Material_0: THREE.Mesh
    Cube071_Material_0: THREE.Mesh
    Cube005_Material002_0: THREE.Mesh
    Cube069_Material002_0: THREE.Mesh
    Cube072_Material002_0: THREE.Mesh
    Cube073_Material001_0: THREE.Mesh
    Cube073_Material002_0: THREE.Mesh
    Cube074_Material003_0: THREE.Mesh
    Cube075_Material003_0: THREE.Mesh
    Cube130_Material003_0: THREE.Mesh
    Cube131_Material003_0: THREE.Mesh
    Cube132_Material003_0: THREE.Mesh
    Cube133_Material003_0: THREE.Mesh
    Cube134_Material003_0: THREE.Mesh
    Cube135_Material003_0: THREE.Mesh
    Cube136_Material003_0: THREE.Mesh
    Cube137_Material003_0: THREE.Mesh
    Cube138_Material003_0: THREE.Mesh
    Cube139_Material003_0: THREE.Mesh
    Cube140_Material003_0: THREE.Mesh
    Cube141_Material003_0: THREE.Mesh
    Cube142_Material003_0: THREE.Mesh
    Cube143_Material003_0: THREE.Mesh
    Cube144_Material003_0: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    ['Cube.116__0']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: React.ComponentProps<'group'>) {
  const group = React.useRef<THREE.Group>(null!)
  const { nodes, materials, animations } = useGLTF('/assets/models/caves/cave.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="130a23792b5c4fdc918d8ff424b96d8efbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Camera" position={[107.548, 131.926, 1569.591]} rotation={[2.828, 1.501, -2.829]} scale={100}>
                  <group name="Object_5" />
                </group>
                <group name="Point" position={[159.509, 591.933, -41.498]} scale={100}>
                  <group name="Object_7" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_8" />
                  </group>
                </group>
                <group name="Cube001" position={[402.929, 560.851, -235.049]} rotation={[-1.776, -0.501, 1.161]} scale={[12.095, 12.277, 87.305]}>
                  <mesh name="Cube001_Material001_0" geometry={nodes.Cube001_Material001_0.geometry} material={materials['Material.001']} />
                  <mesh name="Cube001_Material002_0" geometry={nodes.Cube001_Material002_0.geometry} material={materials['Material.002']} />
                </group>
                <group name="Point001" position={[371.734, 617.675, -247.975]} rotation={[0, -0.357, 0.057]} scale={100}>
                  <group name="Object_13" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_14" />
                  </group>
                </group>
                <group name="Cube002" position={[793.854, 559.94, -1002.011]} rotation={[-Math.PI / 2, -0.481, Math.PI / 2]} scale={[12.095, 12.277, 87.305]}>
                  <mesh name="Cube002_Material001_0" geometry={nodes.Cube002_Material001_0.geometry} material={materials['Material.001']} />
                  <mesh name="Cube002_Material002_0" geometry={nodes.Cube002_Material002_0.geometry} material={materials['Material.002']} />
                </group>
                <group name="Point002" position={[763.486, 618.651, -1002.816]} scale={100}>
                  <group name="Object_19" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_20" />
                  </group>
                </group>
                <group name="Cube003" position={[628.298, 561.667, -1755.776]} rotation={[-1.346, 0.546, -2.069]} scale={[12.095, 12.277, 87.305]}>
                  <mesh name="Cube003_Material001_0" geometry={nodes.Cube003_Material001_0.geometry} material={materials['Material.001']} />
                  <mesh name="Cube003_Material002_0" geometry={nodes.Cube003_Material002_0.geometry} material={materials['Material.002']} />
                </group>
                <group name="Point003" position={[662.029, 616.858, -1742.16]} rotation={[3.14, 0.01, -3.028]} scale={100}>
                  <group name="Object_25" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_26" />
                  </group>
                </group>
                <group name="Point004" position={[862.585, 676.141, -1764.189]} scale={100}>
                  <group name="Object_28" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_29" />
                  </group>
                </group>
                <group name="Point005" position={[395.537, 630.802, -731.78]} scale={100}>
                  <group name="Object_31" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_32" />
                  </group>
                </group>
                <group name="Point006" position={[-22.354, 605.925, 689.945]} scale={100}>
                  <group name="Object_34" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_35" />
                  </group>
                </group>
                <group name="Cube011" position={[1730.917, 414.602, -4557.941]} rotation={[-1.116, -0.068, 0.883]} scale={20.714}>
                  <mesh name="Cube011_Material_0" geometry={nodes.Cube011_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube012" position={[1771.045, 439.104, -4459.172]} rotation={[-1.258, -0.79, 0.323]} scale={[46.053, 23.97, 32.829]}>
                  <mesh name="Cube012_Material_0" geometry={nodes.Cube012_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube013" position={[1769.489, 411.18, -4430.179]} rotation={[-2.889, -1.286, -0.126]} scale={[20.924, 10.891, 14.915]}>
                  <mesh name="Cube013_Material_0" geometry={nodes.Cube013_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube014" position={[1723.397, 477.532, -4492.93]} rotation={[-0.478, 0.576, 1.365]} scale={[22.556, 11.74, 16.079]}>
                  <mesh name="Cube014_Material_0" geometry={nodes.Cube014_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube015" position={[1727.927, 454.04, -4426.197]} rotation={[-0.478, 0.576, 1.365]} scale={[10.072, 5.242, 7.18]}>
                  <mesh name="Cube015_Material_0" geometry={nodes.Cube015_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube016" position={[1737.271, 465.318, -4526.147]} rotation={[-0.854, 0.183, 1.339]} scale={[18.186, 9.465, 12.964]}>
                  <mesh name="Cube016_Material_0" geometry={nodes.Cube016_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube017" position={[1754.799, 439.104, -4345.273]} rotation={[-1.767, -0.819, -0.369]} scale={[46.053, 23.97, 32.829]}>
                  <mesh name="Cube017_Material_0" geometry={nodes.Cube017_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube018" position={[2061.835, 431.512, -3784.947]} rotation={[-1.184, -0.681, 0.645]} scale={[48.083, 25.026, 34.276]}>
                  <mesh name="Cube018_Material_0" geometry={nodes.Cube018_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube019" position={[2056.741, 450.947, -3822.691]} rotation={[-0.731, 0.802, 1.536]} scale={[23.55, 12.258, 16.788]}>
                  <mesh name="Cube019_Material_0" geometry={nodes.Cube019_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube020" position={[2008.838, 455.432, -3728.352]} rotation={[-0.564, 0.34, 1.238]} scale={[10.516, 5.473, 7.496]}>
                  <mesh name="Cube020_Material_0" geometry={nodes.Cube020_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube021" position={[2047.097, 496.614, -3792.523]} rotation={[-1.042, 0.274, 1.31]} scale={[48.083, 25.026, 34.276]}>
                  <mesh name="Cube021_Material_0" geometry={nodes.Cube021_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube022" position={[2046.609, 406.174, -3671.347]} rotation={[0.085, -0.833, 0.017]} scale={[48.083, 25.026, 34.276]}>
                  <mesh name="Cube022_Material_0" geometry={nodes.Cube022_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube023" position={[1393.561, 467.868, -2244.723]} rotation={[-2.354, 0.716, -2.439]} scale={49.938}>
                  <mesh name="Cube023_Material_0" geometry={nodes.Cube023_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube024" position={[1451.432, 452.023, -2373.065]} rotation={[-1.232, 1.207, 2.781]} scale={[55.127, 28.693, 39.297]}>
                  <mesh name="Cube024_Material_0" geometry={nodes.Cube024_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube025" position={[1393.749, 425.608, -2371.649]} rotation={[0.387, 0.925, 2.016]} scale={[25.046, 13.036, 17.854]}>
                  <mesh name="Cube025_Material_0" geometry={nodes.Cube025_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube026" position={[1428.264, 477.349, -2363.078]} rotation={[-2.552, -0.059, -1.61]} scale={[27.001, 14.053, 19.247]}>
                  <mesh name="Cube026_Material_0" geometry={nodes.Cube026_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube027" position={[1541.702, 457.669, -2402.801]} rotation={[-2.552, -0.059, -1.61]} scale={[12.057, 6.275, 8.595]}>
                  <mesh name="Cube027_Material_0" geometry={nodes.Cube027_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube028" position={[1474.071, 524.145, -2370.301]} rotation={[-2.219, 0.432, -2.067]} scale={[55.127, 28.693, 39.297]}>
                  <mesh name="Cube028_Material_0" geometry={nodes.Cube028_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube029" position={[1551.093, 445.55, -2486.928]} rotation={[-0.636, 0.975, 1.923]} scale={[60.66, 36.876, 45.751]}>
                  <mesh name="Cube029_Material_0" geometry={nodes.Cube029_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube030" position={[1433.982, 438.829, -2141.325]} rotation={[0.387, 0.925, 2.016]} scale={[43.705, 22.748, 31.155]}>
                  <mesh name="Cube030_Material_0" geometry={nodes.Cube030_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube031" position={[1736.199, 347.865, -3133.658]} rotation={[-1.206, 0.071, -1.671]} scale={[12.708, 6.277, 8.664]}>
                  <mesh name="Cube031_Material_0" geometry={nodes.Cube031_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube032" position={[1722.02, 366.949, -2922.161]} rotation={[-2.623, 0.071, -1.671]} scale={[12.057, 6.275, 8.595]}>
                  <mesh name="Cube032_Material_0" geometry={nodes.Cube032_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube033" position={[1722.02, 360.46, -3068.141]} rotation={[-2.623, 0.071, -1.671]} scale={[18.571, 9.666, 13.238]}>
                  <mesh name="Cube033_Material_0" geometry={nodes.Cube033_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube034" position={[1202.087, 449.604, -3248.027]} rotation={[-0.936, -0.743, 0.694]} scale={[46.053, 23.97, 32.829]}>
                  <mesh name="Cube034_Material_0" geometry={nodes.Cube034_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube035" position={[1748.971, 359.339, -3184.444]} rotation={[-2.402, 0.444, 1.609]} scale={[10.072, 5.242, 7.18]}>
                  <mesh name="Cube035_Material_0" geometry={nodes.Cube035_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube036" position={[1183.164, 508.415, -3225.391]} rotation={[0.156, 0.129, 1.055]} scale={[34.695, 18.058, 24.732]}>
                  <mesh name="Cube036_Material_0" geometry={nodes.Cube036_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube037" position={[1167.84, 450.271, -3148.117]} rotation={[-1.401, -0.904, 0.026]} scale={[46.053, 23.97, 32.829]}>
                  <mesh name="Cube037_Material_0" geometry={nodes.Cube037_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube038" position={[1764.59, 379.688, -3241.044]} rotation={[1.076, 0.444, 1.609]} scale={[12.722, 6.621, 9.069]}>
                  <mesh name="Cube038_Material_0" geometry={nodes.Cube038_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube039" position={[753.288, 460.593, -1891.091]} rotation={[-0.879, -0.951, 0.78]} scale={[70.802, 36.852, 50.471]}>
                  <mesh name="Cube039_Material_0" geometry={nodes.Cube039_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube040" position={[686.916, 448.378, -1824.914]} rotation={[-0.671, 0.577, 1.763]} scale={[15.485, 8.06, 11.038]}>
                  <mesh name="Cube040_Material_0" geometry={nodes.Cube040_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube041" position={[704.185, 543.477, -1860.244]} rotation={[0.127, 0.075, 1.265]} scale={[53.34, 27.763, 38.023]}>
                  <mesh name="Cube041_Material_0" geometry={nodes.Cube041_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube042" position={[671.453, 451.193, -1742.298]} rotation={[-1.502, -1.112, -0.083]} scale={[70.802, 36.852, 50.471]}>
                  <mesh name="Cube042_Material_0" geometry={nodes.Cube042_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube043" position={[703.758, 361.662, -1838.193]} rotation={[-0.671, 0.577, 1.763]} scale={[19.558, 10.18, 13.942]}>
                  <mesh name="Cube043_Material_0" geometry={nodes.Cube043_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube044" position={[-59.563, 431.512, -328.602]} rotation={[-1.815, 0.736, -2.715]} scale={[48.083, 25.026, 34.276]}>
                  <mesh name="Cube044_Material_0" geometry={nodes.Cube044_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube045" position={[-43.418, 456.661, -367.94]} rotation={[-2.51, -0.666, -1.753]} scale={[20.508, 10.674, 14.619]}>
                  <mesh name="Cube045_Material_0" geometry={nodes.Cube045_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube046" position={[2.458, 421.512, -362.175]} rotation={[-2.602, -0.191, -1.998]} scale={[9.058, 4.714, 6.457]}>
                  <mesh name="Cube046_Material_0" geometry={nodes.Cube046_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube047" position={[31.365, 417.36, -347.527]} rotation={[-2.685, 0.946, -0.843]} scale={[19.968, 10.393, 14.234]}>
                  <mesh name="Cube047_Material_0" geometry={nodes.Cube047_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube048" position={[-24.84, 406.174, -437.831]} rotation={[3.034, 1.007, -3.097]} scale={[48.083, 25.026, 34.276]}>
                  <mesh name="Cube048_Material_0" geometry={nodes.Cube048_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube049" position={[278.799, 410.845, 1079.897]} rotation={[2.978, 0.295, -1.737]} scale={[46.053, 23.97, 32.829]}>
                  <mesh name="Cube049_Material_0" geometry={nodes.Cube049_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube050" position={[288.953, 457.141, 1099.137]} rotation={[2.943, -0.878, -2.021]} scale={[34.695, 18.058, 24.732]}>
                  <mesh name="Cube050_Material_0" geometry={nodes.Cube050_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube051" position={[280.126, 362.914, 1031.401]} rotation={[2.943, -0.878, -2.021]} scale={[5.964, 3.104, 4.251]}>
                  <mesh name="Cube051_Material_0" geometry={nodes.Cube051_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube052" position={[267.324, 370.924, 1019.651]} rotation={[2.943, -0.878, -2.021]} scale={[12.018, 6.255, 8.567]}>
                  <mesh name="Cube052_Material_0" geometry={nodes.Cube052_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube053" position={[546.456, 398.917, -411.506]} rotation={[-2.742, 0.153, 2.854]} scale={[20.508, 10.674, 14.619]}>
                  <mesh name="Cube053_Material_0" geometry={nodes.Cube053_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube054" position={[508.149, 390.652, -332.836]} rotation={[-3.014, 0.834, 3.109]} scale={[7.14, 3.716, 5.09]}>
                  <mesh name="Cube054_Material_0" geometry={nodes.Cube054_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube055" position={[475.977, 396.007, -295.55]} rotation={[-0.993, 0.658, -3.089]} scale={[15.573, 8.106, 11.101]}>
                  <mesh name="Cube055_Material_0" geometry={nodes.Cube055_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube056" position={[1538.856, 398.335, -3998.257]} rotation={[-0.615, 0.43, 1.638]} scale={[10.072, 5.242, 7.18]}>
                  <mesh name="Cube056_Material_0" geometry={nodes.Cube056_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube057" position={[1569.967, 399.01, -4081.276]} rotation={[1.718, 0.43, 1.638]} scale={[4.721, 2.457, 3.366]}>
                  <mesh name="Cube057_Material_0" geometry={nodes.Cube057_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube058" position={[1415.566, 559.94, -3698.15]} rotation={[-1.179, 0.286, -2.542]} scale={[12.095, 12.277, 87.305]}>
                  <mesh name="Cube058_Material001_0" geometry={nodes.Cube058_Material001_0.geometry} material={materials['Material.001']} />
                  <mesh name="Cube058_Material002_0" geometry={nodes.Cube058_Material002_0.geometry} material={materials['Material.002']} />
                </group>
                <group name="Point007" position={[1434.686, 618.468, -3674.014]} rotation={[-Math.PI, 0.501, Math.PI]} scale={100}>
                  <group name="Object_134" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_135" />
                  </group>
                </group>
                <group name="Cube059" position={[2215.111, 559.94, -4180.962]} rotation={[-1.695, -0.466, 1.3]} scale={[12.095, 12.277, 87.305]}>
                  <mesh name="Cube059_Material001_0" geometry={nodes.Cube059_Material001_0.geometry} material={materials['Material.001']} />
                  <mesh name="Cube059_Material002_0" geometry={nodes.Cube059_Material002_0.geometry} material={materials['Material.002']} />
                </group>
                <group name="Point008" position={[2185.042, 618.294, -4187.679]} rotation={[0, 0.172, 0]} scale={100}>
                  <group name="Object_140" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_141" />
                  </group>
                </group>
                <group name="Cube060" position={[1003.152, 618.738, -2529.64]} rotation={[-1.121, 0.329, -2.518]} scale={[12.095, 12.277, 87.305]}>
                  <mesh name="Cube060_Material001_0" geometry={nodes.Cube060_Material001_0.geometry} material={materials['Material.001']} />
                  <mesh name="Cube060_Material002_0" geometry={nodes.Cube060_Material002_0.geometry} material={materials['Material.002']} />
                </group>
                <group name="Point009" position={[1024.249, 675.349, -2502.962]} rotation={[-3.092, 0.463, -3.108]} scale={100}>
                  <group name="Object_146" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_147" />
                  </group>
                </group>
                <group name="Cube061" position={[1467.786, 626.274, -2556.13]} rotation={[-1.762, -0.563, 1.216]} scale={[12.409, 15.088, 89.686]}>
                  <mesh name="Cube061_Material001_0" geometry={nodes.Cube061_Material001_0.geometry} material={materials['Material.001']} />
                  <mesh name="Cube061_Material002_0" geometry={nodes.Cube061_Material002_0.geometry} material={materials['Material.002']} />
                </group>
                <group name="Point010" position={[1431.487, 682.218, -2566.64]} rotation={[-0.041, 0.113, 0.107]} scale={[126.324, 100.744, 100.384]}>
                  <group name="Object_152" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_153" />
                  </group>
                </group>
                <group name="Cube063" position={[1523.393, 586.464, -2535.584]} rotation={[Math.PI / 2, 0, -2.751]} scale={[-29.751, -25.292, -283.628]}>
                  <mesh name="Cube063_Material002_0" geometry={nodes.Cube063_Material002_0.geometry} material={materials['Material.002']} />
                </group>
                <group name="Cube062" position={[1045.537, 586.464, -2665.661]} rotation={[Math.PI / 2, 0, -2.634]} scale={[-29.193, -25.943, -283.628]}>
                  <mesh name="Cube062_Material002_0" geometry={nodes.Cube062_Material002_0.geometry} material={materials['Material.002']} />
                </group>
                <group name="Cube064" position={[1275.632, 834.503, -2602.864]} rotation={[3.076, -1.255, -1.628]} scale={[-22.51, -23.329, -242.264]}>
                  <mesh name="Cube064_Material002_0" geometry={nodes.Cube064_Material002_0.geometry} material={materials['Material.002']} />
                </group>
                <group name="Point011" position={[1938.864, 580.547, -5236.46]} scale={100}>
                  <group name="Object_161" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_162" />
                  </group>
                </group>
                <group name="Point012" position={[2077.973, 580.547, -4762.829]} scale={100}>
                  <group name="Object_164" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_165" />
                  </group>
                </group>
                <group name="Point013" position={[1906.817, 591.933, -6960.838]} scale={100}>
                  <group name="Object_167" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_168" />
                  </group>
                </group>
                <group name="Cube065" position={[2149.869, 559.94, -7160.251]} rotation={[-Math.PI / 2, -0.481, Math.PI / 2]} scale={[12.095, 12.277, 87.305]}>
                  <mesh name="Cube065_Material001_0" geometry={nodes.Cube065_Material001_0.geometry} material={materials['Material.001']} />
                  <mesh name="Cube065_Material002_0" geometry={nodes.Cube065_Material002_0.geometry} material={materials['Material.002']} />
                </group>
                <group name="Point014" position={[2119.397, 618.585, -7161.453]} scale={100}>
                  <group name="Object_173" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_174" />
                  </group>
                </group>
                <group name="Cube066" position={[2123.56, 559.94, -8171.862]} rotation={[-Math.PI / 2, -0.481, Math.PI / 2]} scale={[12.095, 12.277, 87.305]}>
                  <mesh name="Cube066_Material001_0" geometry={nodes.Cube066_Material001_0.geometry} material={materials['Material.001']} />
                  <mesh name="Cube066_Material002_0" geometry={nodes.Cube066_Material002_0.geometry} material={materials['Material.002']} />
                </group>
                <group name="Point015" position={[2093.088, 618.585, -8173.063]} scale={100}>
                  <group name="Object_179" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_180" />
                  </group>
                </group>
                <group name="Cube067" position={[1820.078, 559.94, -8526.939]} rotation={[-1.359, 0.436, -2.041]} scale={[12.095, 12.277, 87.305]}>
                  <mesh name="Cube067_Material001_0" geometry={nodes.Cube067_Material001_0.geometry} material={materials['Material.001']} />
                  <mesh name="Cube067_Material002_0" geometry={nodes.Cube067_Material002_0.geometry} material={materials['Material.002']} />
                </group>
                <group name="Point016" position={[1849.052, 618.022, -8514.555]} rotation={[-Math.PI, 0.01, Math.PI]} scale={100}>
                  <group name="Object_185" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_186" />
                  </group>
                </group>
                <group name="Point017" position={[2214.008, 585.231, -8668.185]} scale={100}>
                  <group name="Object_188" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_189" />
                  </group>
                </group>
                <group name="Point018" position={[2004.908, 559.804, -7651.12]} scale={100}>
                  <group name="Object_191" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_192" />
                  </group>
                </group>
                <group name="Point019" position={[413.943, 1153.85, 3072.042]} scale={100}>
                  <group name="Object_194" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_195" />
                  </group>
                </group>
                <group name="Cube076" position={[3531.671, 414.602, -11482.678]} rotation={[-1.116, -0.068, 0.883]} scale={20.714}>
                  <mesh name="Cube076_Material_0" geometry={nodes.Cube076_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube077" position={[3571.799, 439.104, -11378.513]} rotation={[-1.258, -0.79, 0.323]} scale={[46.053, 23.97, 32.829]}>
                  <mesh name="Cube077_Material_0" geometry={nodes.Cube077_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube078" position={[3606.492, 411.18, -11397.871]} rotation={[-2.549, -1.286, -0.126]} scale={[20.924, 10.891, 14.915]}>
                  <mesh name="Cube078_Material_0" geometry={nodes.Cube078_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube079" position={[3593.885, 452.432, -11393.558]} rotation={[-0.478, 0.576, 1.365]} scale={[22.556, 11.74, 16.079]}>
                  <mesh name="Cube079_Material_0" geometry={nodes.Cube079_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube080" position={[3528.68, 454.04, -11345.537]} rotation={[-0.478, 0.576, 1.365]} scale={[10.072, 5.242, 7.18]}>
                  <mesh name="Cube080_Material_0" geometry={nodes.Cube080_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube081" position={[3538.025, 464.78, -11445.488]} rotation={[-0.854, 0.183, 1.339]} scale={[18.186, 9.465, 12.964]}>
                  <mesh name="Cube081_Material_0" geometry={nodes.Cube081_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube082" position={[3549.698, 439.104, -11264.613]} rotation={[-1.767, -0.819, -0.369]} scale={[46.053, 23.97, 32.829]}>
                  <mesh name="Cube082_Material_0" geometry={nodes.Cube082_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube083" position={[3809.144, 431.512, -10704.288]} rotation={[-1.184, -0.681, 0.645]} scale={[48.083, 25.026, 34.276]}>
                  <mesh name="Cube083_Material_0" geometry={nodes.Cube083_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube084" position={[3804.05, 450.947, -10742.031]} rotation={[-0.731, 0.802, 1.536]} scale={[23.55, 12.258, 16.788]}>
                  <mesh name="Cube084_Material_0" geometry={nodes.Cube084_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube085" position={[3756.146, 455.432, -10647.692]} rotation={[-0.564, 0.34, 1.238]} scale={[10.516, 5.473, 7.496]}>
                  <mesh name="Cube085_Material_0" geometry={nodes.Cube085_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube086" position={[3794.405, 496.614, -10711.863]} rotation={[-1.042, 0.274, 1.31]} scale={[48.083, 25.026, 34.276]}>
                  <mesh name="Cube086_Material_0" geometry={nodes.Cube086_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube087" position={[3793.917, 406.174, -10590.688]} rotation={[0.085, -0.833, 0.017]} scale={[48.083, 25.026, 34.276]}>
                  <mesh name="Cube087_Material_0" geometry={nodes.Cube087_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube088" position={[3414.462, 434.122, -9159.31]} rotation={[-2.337, 0.827, -2.565]} scale={62.792}>
                  <mesh name="Cube088_Material_0" geometry={nodes.Cube088_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube089" position={[3508.687, 406.908, -9292.081]} rotation={[-0.973, 1.157, 2.425]} scale={[55.127, 28.693, 39.297]}>
                  <mesh name="Cube089_Material_0" geometry={nodes.Cube089_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube090" position={[3450.83, 381.316, -9297.053]} rotation={[0.28, 0.785, 2.063]} scale={[25.046, 13.036, 17.854]}>
                  <mesh name="Cube090_Material_0" geometry={nodes.Cube090_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube091" position={[3484.887, 433.148, -9287.29]} rotation={[-2.623, 0.071, -1.671]} scale={[27.001, 14.053, 19.247]}>
                  <mesh name="Cube091_Material_0" geometry={nodes.Cube091_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube092" position={[3602.352, 409.376, -9308.977]} rotation={[-2.623, 0.071, -1.671]} scale={[12.057, 6.275, 8.595]}>
                  <mesh name="Cube092_Material_0" geometry={nodes.Cube092_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube093" position={[3532.246, 478.782, -9291.168]} rotation={[-2.237, 0.533, -2.182]} scale={[55.127, 28.693, 39.297]}>
                  <mesh name="Cube093_Material_0" geometry={nodes.Cube093_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube094" position={[3623.271, 391.107, -9389.854]} rotation={[-0.583, 0.867, 1.766]} scale={[60.66, 36.876, 45.751]}>
                  <mesh name="Cube094_Material_0" geometry={nodes.Cube094_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube095" position={[3458.397, 410.683, -9064.839]} rotation={[0.28, 0.785, 2.063]} scale={[43.705, 22.748, 31.155]}>
                  <mesh name="Cube095_Material_0" geometry={nodes.Cube095_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube096" position={[3771.125, 325.281, -9880.961]} rotation={[-1.206, 0.071, -1.671]} scale={[12.708, 6.277, 8.664]}>
                  <mesh name="Cube096_Material_0" geometry={nodes.Cube096_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube097" position={[3765.1, 344.364, -9669.464]} rotation={[-2.623, 0.071, -1.671]} scale={[12.057, 6.275, 8.595]}>
                  <mesh name="Cube097_Material_0" geometry={nodes.Cube097_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube098" position={[3765.1, 337.875, -9815.443]} rotation={[-2.623, 0.071, -1.671]} scale={[18.571, 9.666, 13.238]}>
                  <mesh name="Cube098_Material_0" geometry={nodes.Cube098_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube099" position={[3284.049, 443.919, -10160.35]} rotation={[-1.12, -1.051, 0.495]} scale={[46.053, 23.97, 32.829]}>
                  <mesh name="Cube099_Material_0" geometry={nodes.Cube099_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube100" position={[3225.397, 435.974, -10132.085]} rotation={[-0.61, 0.43, 1.638]} scale={[10.072, 5.242, 7.18]}>
                  <mesh name="Cube100_Material_0" geometry={nodes.Cube100_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube101" position={[3248.996, 497.831, -10146.424]} rotation={[0.127, -0.106, 1.288]} scale={[34.695, 18.058, 24.732]}>
                  <mesh name="Cube101_Material_0" geometry={nodes.Cube101_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube102" position={[3225.313, 437.805, -10072.783]} rotation={[-1.863, -1.091, -0.486]} scale={[46.053, 23.97, 32.829]}>
                  <mesh name="Cube102_Material_0" geometry={nodes.Cube102_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube103" position={[3242.711, 379.57, -10132.085]} rotation={[-0.61, 0.43, 1.638]} scale={[12.722, 6.621, 9.069]}>
                  <mesh name="Cube103_Material_0" geometry={nodes.Cube103_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube104" position={[1966.019, 459.425, -8676.233]} rotation={[-1.261, -1.082, 0.334]} scale={[70.802, 36.852, 50.471]}>
                  <mesh name="Cube104_Material_0" geometry={nodes.Cube104_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube105" position={[1884.579, 447.21, -8629.844]} rotation={[-0.591, 0.361, 1.587]} scale={[15.485, 8.06, 11.038]}>
                  <mesh name="Cube105_Material_0" geometry={nodes.Cube105_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube106" position={[1910.532, 542.31, -8659.388]} rotation={[0.129, -0.189, 1.299]} scale={[53.34, 27.763, 38.023]}>
                  <mesh name="Cube106_Material_0" geometry={nodes.Cube106_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube107" position={[1864.814, 450.025, -8549.601]} rotation={[-2.008, -1.061, -0.651]} scale={[70.802, 36.852, 50.471]}>
                  <mesh name="Cube107_Material_0" geometry={nodes.Cube107_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube108" position={[1904.32, 360.494, -8638.226]} rotation={[-0.591, 0.361, 1.587]} scale={[19.558, 10.18, 13.942]}>
                  <mesh name="Cube108_Material_0" geometry={nodes.Cube108_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube109" position={[1687.745, 431.512, -7247.942]} rotation={[-1.815, 0.736, -2.715]} scale={[48.083, 25.026, 34.276]}>
                  <mesh name="Cube109_Material_0" geometry={nodes.Cube109_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube110" position={[1703.89, 456.661, -7287.281]} rotation={[-2.51, -0.666, -1.753]} scale={[20.508, 10.674, 14.619]}>
                  <mesh name="Cube110_Material_0" geometry={nodes.Cube110_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube111" position={[1749.766, 421.512, -7281.516]} rotation={[-2.602, -0.191, -1.998]} scale={[9.058, 4.714, 6.457]}>
                  <mesh name="Cube111_Material_0" geometry={nodes.Cube111_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube112" position={[1778.673, 417.36, -7266.867]} rotation={[-2.685, 0.946, -0.843]} scale={[19.968, 10.393, 14.234]}>
                  <mesh name="Cube112_Material_0" geometry={nodes.Cube112_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube113" position={[1722.468, 406.174, -7357.172]} rotation={[3.034, 1.007, -3.097]} scale={[48.083, 25.026, 34.276]}>
                  <mesh name="Cube113_Material_0" geometry={nodes.Cube113_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube114" position={[2026.107, 410.845, -5839.443]} rotation={[2.978, 0.295, -1.737]} scale={[46.053, 23.97, 32.829]}>
                  <mesh name="Cube114_Material_0" geometry={nodes.Cube114_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube115" position={[2036.261, 457.141, -5820.204]} rotation={[2.943, -0.878, -2.021]} scale={[34.695, 18.058, 24.732]}>
                  <mesh name="Cube115_Material_0" geometry={nodes.Cube115_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube116" position={[2027.434, 362.914, -5887.939]} rotation={[2.943, -0.878, -2.021]} scale={[5.964, 3.104, 4.251]}>
                  <mesh name="Cube116__0" geometry={nodes.Cube116__0.geometry} material={materials['Cube.116__0']} />
                </group>
                <group name="Cube117" position={[2014.632, 370.924, -5899.69]} rotation={[2.943, -0.878, -2.021]} scale={[12.018, 6.255, 8.567]}>
                  <mesh name="Cube117_Material_0" geometry={nodes.Cube117_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube118" position={[2207.424, 389.359, -7325.943]} rotation={[-3.056, 0.419, -2.413]} scale={[20.508, 10.674, 14.619]}>
                  <mesh name="Cube118_Material_0" geometry={nodes.Cube118_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube119" position={[2224.517, 372.63, -7275.209]} rotation={[2.996, 0.831, -2.806]} scale={[7.14, 3.716, 5.09]}>
                  <mesh name="Cube119__0" geometry={nodes.Cube119__0.geometry} material={materials['Cube.116__0']} />
                </group>
                <group name="Cube120" position={[2195.429, 388.868, -7237.923]} rotation={[-0.851, 0.856, 2.989]} scale={[15.573, 8.106, 11.101]}>
                  <mesh name="Cube120_Material_0" geometry={nodes.Cube120_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube121" position={[3345.222, 398.335, -10917.598]} rotation={[-0.615, 0.43, 1.638]} scale={[10.072, 5.242, 7.18]}>
                  <mesh name="Cube121_Material_0" geometry={nodes.Cube121_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube122" position={[3341.625, 393.234, -10894.854]} rotation={[1.718, 0.43, 1.638]} scale={[4.721, 2.457, 3.366]}>
                  <mesh name="Cube122_Material_0" geometry={nodes.Cube122_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube123" position={[3241.479, 559.94, -10290.927]} rotation={[-1.505, 0.477, -1.714]} scale={[12.095, 12.277, 87.305]}>
                  <mesh name="Cube123_Material001_0" geometry={nodes.Cube123_Material001_0.geometry} material={materials['Material.001']} />
                  <mesh name="Cube123_Material002_0" geometry={nodes.Cube123_Material002_0.geometry} material={materials['Material.002']} />
                </group>
                <group name="Point020" position={[3271.554, 618.585, -10285.883]} rotation={[-Math.PI, -0.286, -Math.PI]} scale={100}>
                  <group name="Object_294" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_295" />
                  </group>
                </group>
                <group name="Cube124" position={[3993.914, 559.94, -11100.302]} rotation={[-1.695, -0.466, 1.3]} scale={[12.095, 12.277, 87.305]}>
                  <mesh name="Cube124_Material001_0" geometry={nodes.Cube124_Material001_0.geometry} material={materials['Material.001']} />
                  <mesh name="Cube124_Material002_0" geometry={nodes.Cube124_Material002_0.geometry} material={materials['Material.002']} />
                </group>
                <group name="Point021" position={[3966.375, 613.887, -11107.42]} rotation={[0, 0.172, 0]} scale={100}>
                  <group name="Object_300" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_301" />
                  </group>
                </group>
                <group name="Cube125" position={[2578.798, 561.077, -9141.834]} rotation={[-1.032, 0.118, -2.913]} scale={[12.095, 12.277, 87.305]}>
                  <mesh name="Cube125_Material001_0" geometry={nodes.Cube125_Material001_0.geometry} material={materials['Material.001']} />
                  <mesh name="Cube125_Material002_0" geometry={nodes.Cube125_Material002_0.geometry} material={materials['Material.002']} />
                </group>
                <group name="Point022" position={[2586.591, 617.313, -9108.02]} rotation={[-3.07, 0.901, Math.PI]} scale={100}>
                  <group name="Object_306" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_307" />
                  </group>
                </group>
                <group name="Cube126" position={[3590.564, 558.054, -9484.033]} rotation={[-1.655, -0.324, 1.449]} scale={[12.095, 12.277, 87.305]}>
                  <mesh name="Cube126_Material001_0" geometry={nodes.Cube126_Material001_0.geometry} material={materials['Material.001']} />
                  <mesh name="Cube126_Material002_0" geometry={nodes.Cube126_Material002_0.geometry} material={materials['Material.002']} />
                </group>
                <group name="Point023" position={[3568.26, 619.817, -9488.395]} rotation={[0.02, 0.293, -0.161]} scale={100}>
                  <group name="Object_312" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_313" />
                  </group>
                </group>
                <group name="Cube127" position={[3641.021, 522.665, -9480.429]} rotation={[Math.PI / 2, 0, -2.932]} scale={[-24.061, -24.23, -283.628]}>
                  <mesh name="Cube127_Material002_0" geometry={nodes.Cube127_Material002_0.geometry} material={materials['Material.002']} />
                </group>
                <group name="Cube128" position={[3248.121, 522.665, -9540.798]} rotation={[Math.PI / 2, 0, -2.814]} scale={[-24.061, -24.23, -283.628]}>
                  <mesh name="Cube128_Material002_0" geometry={nodes.Cube128_Material002_0.geometry} material={materials['Material.002']} />
                </group>
                <group name="Cube129" position={[3437.338, 770.705, -9511.569]} rotation={[2.991, -1.435, -1.715]} scale={[-22.507, -22.665, -194.042]}>
                  <mesh name="Cube129_Material002_0" geometry={nodes.Cube129_Material002_0.geometry} material={materials['Material.002']} />
                </group>
                <group name="Point024" position={[3686.172, 580.547, -12155.801]} scale={100}>
                  <group name="Object_321" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_322" />
                  </group>
                </group>
                <group name="Point025" position={[3825.281, 580.547, -11682.17]} scale={100}>
                  <group name="Object_324" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_325" />
                  </group>
                </group>
                <group name="Cube006" position={[1605.065, 559.94, -5556.819]} rotation={[-1.718, 0.46, -1.248]} scale={[12.095, 12.277, 87.305]}>
                  <mesh name="Cube006_Material001_0" geometry={nodes.Cube006_Material001_0.geometry} material={materials['Material.001']} />
                  <mesh name="Cube006_Material002_0" geometry={nodes.Cube006_Material002_0.geometry} material={materials['Material.002']} />
                </group>
                <group name="Point026" position={[1633.363, 618.923, -5565.328]} rotation={[-Math.PI, -0.702, -Math.PI]} scale={100}>
                  <group name="Object_330" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_331" />
                  </group>
                </group>
                <group name="Cube068" position={[-261.599, 560.851, 1035.309]} rotation={[-1.684, 0.527, -1.349]} scale={[12.095, 12.277, 87.305]}>
                  <mesh name="Cube068_Material001_0" geometry={nodes.Cube068_Material001_0.geometry} material={materials['Material.001']} />
                  <mesh name="Cube068_Material002_0" geometry={nodes.Cube068_Material002_0.geometry} material={materials['Material.002']} />
                </group>
                <group name="Point027" position={[-228.24, 617.675, 1030.078]} rotation={[-Math.PI, -0.191, -3.085]} scale={100}>
                  <group name="Object_336" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_337" />
                  </group>
                </group>
                <group name="Cube070" position={[337.92, 828.715, 2821.394]} rotation={[-1.507, -0.458, -2.999]} scale={[26.953, 420.485, 275.369]}>
                  <mesh name="Cube070_Material_0" geometry={nodes.Cube070_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube071" position={[587.274, 322.319, 2529.743]} rotation={[-Math.PI / 2, 0, -3.023]} scale={[-1939.796, -2773.956, -52.88]}>
                  <mesh name="Cube071_Material_0" geometry={nodes.Cube071_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cube005" position={[899.063, 743.694, 4015.295]} rotation={[Math.PI / 2, 0, 2.885]} scale={[-36.662, -35.125, -394.195]}>
                  <mesh name="Cube005_Material002_0" geometry={nodes.Cube005_Material002_0.geometry} material={materials['Material.002']} />
                </group>
                <group name="Cube069" position={[335.812, 743.694, 4257.815]} rotation={[Math.PI / 2, 0, 3.003]} scale={[-35.947, -36.051, -394.195]}>
                  <mesh name="Cube069_Material002_0" geometry={nodes.Cube069_Material002_0.geometry} material={materials['Material.002']} />
                </group>
                <group name="Cube072" position={[607.151, 1037.668, 4141.222]} rotation={[0.052, -1.17, 1.624]} scale={[-31.283, -32.337, -299.287]}>
                  <mesh name="Cube072_Material002_0" geometry={nodes.Cube072_Material002_0.geometry} material={materials['Material.002']} />
                </group>
                <group name="Cube073" position={[401.191, 651.013, 4251.741]} rotation={[-1.684, 0.527, -1.349]} scale={[12.095, 12.277, 87.305]}>
                  <mesh name="Cube073_Material001_0" geometry={nodes.Cube073_Material001_0.geometry} material={materials['Material.001']} />
                  <mesh name="Cube073_Material002_0" geometry={nodes.Cube073_Material002_0.geometry} material={materials['Material.002']} />
                </group>
                <group name="Point028" position={[436.953, 710.229, 4242.98]} rotation={[-Math.PI, -0.191, -3.085]} scale={100}>
                  <group name="Object_352" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_353" />
                  </group>
                </group>
                <group name="Cube074" position={[3968.182, 610.441, -11106.805]} rotation={[-1.649, -0.576, -0.251]} scale={6.514}>
                  <mesh name="Cube074_Material003_0" geometry={nodes.Cube074_Material003_0.geometry} material={materials['Material.003']} />
                </group>
                <group name="Cube075" position={[3268.948, 608.425, -10287.249]} rotation={[-1.498, 0.505, -0.149]} scale={6.514}>
                  <mesh name="Cube075_Material003_0" geometry={nodes.Cube075_Material003_0.geometry} material={materials['Material.003']} />
                </group>
                <group name="Cube130" position={[3572.759, 608.425, -9488.039]} rotation={[-1.309, 1.175, -0.283]} scale={6.514}>
                  <mesh name="Cube130_Material003_0" geometry={nodes.Cube130_Material003_0.geometry} material={materials['Material.003']} />
                </group>
                <group name="Cube131" position={[2585.604, 608.258, -9112.768]} rotation={[-2.552, -0.234, 0.16]} scale={6.514}>
                  <mesh name="Cube131_Material003_0" geometry={nodes.Cube131_Material003_0.geometry} material={materials['Material.003']} />
                </group>
                <group name="Cube132" position={[1843.071, 606.715, -8516.883]} rotation={[-2.173, -0.874, -0.731]} scale={6.514}>
                  <mesh name="Cube132_Material003_0" geometry={nodes.Cube132_Material003_0.geometry} material={materials['Material.003']} />
                </group>
                <group name="Cube133" position={[2097.877, 609.559, -8171.481]} rotation={[-Math.PI / 2, -0.518, 0]} scale={6.514}>
                  <mesh name="Cube133_Material003_0" geometry={nodes.Cube133_Material003_0.geometry} material={materials['Material.003']} />
                </group>
                <group name="Cube134" position={[2123.245, 609.302, -7160.265]} rotation={[-Math.PI / 2, -0.518, 0]} scale={6.514}>
                  <mesh name="Cube134_Material003_0" geometry={nodes.Cube134_Material003_0.geometry} material={materials['Material.003']} />
                </group>
                <group name="Cube135" position={[1629.525, 609.302, -5564.271]} rotation={[-1.684, 0.52, 0.316]} scale={6.514}>
                  <mesh name="Cube135_Material003_0" geometry={nodes.Cube135_Material003_0.geometry} material={materials['Material.003']} />
                </group>
                <group name="Cube136" position={[2189.573, 609.174, -4187.294]} rotation={[-Math.PI / 2, -0.534, -0.217]} scale={6.514}>
                  <mesh name="Cube136_Material003_0" geometry={nodes.Cube136_Material003_0.geometry} material={materials['Material.003']} />
                </group>
                <group name="Cube137" position={[1431.821, 609.849, -3677.233]} rotation={[-1.168, 0.285, -0.988]} scale={6.514}>
                  <mesh name="Cube137_Material003_0" geometry={nodes.Cube137_Material003_0.geometry} material={materials['Material.003']} />
                </group>
                <group name="Cube138" position={[1437.406, 673.991, -2565.233]} rotation={[-1.75, -0.528, -0.346]} scale={6.514}>
                  <mesh name="Cube138_Material003_0" geometry={nodes.Cube138_Material003_0.geometry} material={materials['Material.003']} />
                </group>
                <group name="Cube139" position={[1021.379, 666.51, -2507.041]} rotation={[-1.107, 0.372, -0.943]} scale={6.514}>
                  <mesh name="Cube139_Material003_0" geometry={nodes.Cube139_Material003_0.geometry} material={materials['Material.003']} />
                </group>
                <group name="Cube140" position={[657.319, 609.28, -1744.181]} rotation={[-1.303, 0.524, -0.501]} scale={6.514}>
                  <mesh name="Cube140_Material003_0" geometry={nodes.Cube140_Material003_0.geometry} material={materials['Material.003']} />
                </group>
                <group name="Cube141" position={[767.935, 609.62, -1002.435]} rotation={[-Math.PI / 2, -0.465, 0]} scale={6.514}>
                  <mesh name="Cube141_Material003_0" geometry={nodes.Cube141_Material003_0.geometry} material={materials['Material.003']} />
                </group>
                <group name="Cube142" position={[376.462, 608.716, -245.336]} rotation={[-1.769, -0.513, -0.389]} scale={6.514}>
                  <mesh name="Cube142_Material003_0" geometry={nodes.Cube142_Material003_0.geometry} material={materials['Material.003']} />
                </group>
                <group name="Cube143" position={[-233.129, 609.51, 1030.331]} rotation={[-1.666, 0.427, 0.225]} scale={6.514}>
                  <mesh name="Cube143_Material003_0" geometry={nodes.Cube143_Material003_0.geometry} material={materials['Material.003']} />
                </group>
                <group name="Cube144" position={[430.379, 699.18, 4246.441]} rotation={[-1.684, 0.519, 0.225]} scale={6.514}>
                  <mesh name="Cube144_Material003_0" geometry={nodes.Cube144_Material003_0.geometry} material={materials['Material.003']} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/caves/cave.glb')
