/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 /Users/luis/GithubProjects/CaveGame/my-three-app/public/assets/models/caves/Imsurethiswillwork.glb --output src/components/Caves/ImsurethiswillworkModel.tsx --types --bones --public-path /assets/models/caves 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
  }
  materials: {}
  animations: GLTFAction[]
}

export default function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/assets/models/caves/Imsurethiswillwork.glb') as GLTFResult

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[0.23, 0, -1.653]} scale={[5.17, 1, 2.35]} />
    </group>
  )
}

useGLTF.preload('/assets/models/caves/Imsurethiswillwork.glb')
