/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 /Users/luis/GithubProjects/CaveGame/my-three-app/public/assets/models/caves/TunnelPathTEST1.0glb.glb --output src/components/Caves/TunnelPathTEST1.0glbModel.tsx --types --bones --public-path /assets/models/caves 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    TunnelPath: THREE.Mesh
  }
  materials: {}
  animations: GLTFAction[]
}

export default function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/assets/models/caves/TunnelPathTEST1.0glb.glb') as GLTFResult

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.TunnelPath.geometry} material={nodes.TunnelPath.material} />
    </group>
  )
}

useGLTF.preload('/assets/models/caves/TunnelPathTEST1.0glb.glb')
