/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 /Users/luis/GithubProjects/CaveGame/my-three-app/public/assets/models/lamps/lowPolyLantern.glb --output src/components/Lamps/lowPolyLanternModel.tsx --types --bones --public-path /assets/models/lamps 
Author: DLM (https://sketchfab.com/DLM96)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-lantern-b560c86215214429a62519f9285342c4
Title: Low Poly Lantern
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
  }
  materials: {
    Metal: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/assets/models/lamps/lowPolyLantern.glb') as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.45, 0]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Metal} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Glass} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/lamps/lowPolyLantern.glb')
