/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 /Users/luis/GithubProjects/CaveGame/my-three-app/public/assets/models/lamps/oilLamp.glb --output src/components/Lamps/oilLampModel.tsx --types --bones --public-path /assets/models/lamps 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder: THREE.Mesh
    Cylinder001: THREE.Mesh
    Torus: THREE.Mesh
    Cylinder002: THREE.Mesh
  }
  materials: {}
  animations: GLTFAction[]
}

export default function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/assets/models/lamps/oilLamp.glb') as GLTFResult

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[-0.6, 0, 0]} scale={[1, 0.6, 1]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} position={[1.271, 1.449, -0.032]} rotation={[0, 0, -Math.PI / 4]} scale={[0.2, 1.5, 0.2]} />
      <mesh geometry={nodes.Torus.geometry} material={nodes.Torus.material} position={[-1.73, 0.082, 0.017]} rotation={[1.564, -0.803, -3.135]} scale={[0.4, 1, 0.4]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={nodes.Cylinder002.material} position={[2.274, 2.87, -0.053]} scale={0.5} />
    </group>
  )
}

useGLTF.preload('/assets/models/lamps/oilLamp.glb')
