/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 /Users/luis/GithubProjects/CaveGame/my-three-app/public/assets/models/lamps/vintage_oil_can.glb --output src/components/Lamps/vintage_oil_canModel.tsx --types --bones --public-path /assets/models/lamps 
Author: Eks.Art (https://sketchfab.com/Eks.Art)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vintage-oil-can-5efcedc2fc0c4885a3c22b681b16c636
Title: Vintage Oil Can
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    model004_Bakegroup_BAKED_0: THREE.Mesh
  }
  materials: {
    Bakegroup_BAKED: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/assets/models/lamps/vintage_oil_can.glb') as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.model004_Bakegroup_BAKED_0.geometry} material={materials.Bakegroup_BAKED} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/lamps/vintage_oil_can.glb')
