/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 /Users/luis/GithubProjects/CaveGame/my-three-app/public/assets/models/weapons/AlienBlade.glb --output src/components/Weapons/AlienBladeModel.tsx --types --bones --public-path /assets/models/weapons 
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_12: THREE.SkinnedMesh
    Object_8: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
    root_00: THREE.Bone
  }
  materials: {
    Purple_Emis: THREE.MeshStandardMaterial
    ps2_ns_shared_tv_blade: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type BoneRefs = {
  _rootJoint: THREE.Bone | null
  root_00: THREE.Bone | null

  updateMatrixWorld: () => void
}

export default React.forwardRef<any, React.ComponentProps<'group'>>((props, ref) => {
  const group = React.useRef<THREE.Group>(null!)
  const { scene } = useGLTF('/assets/models/weapons/AlienBlade.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult

  // Create refs for each bone
  const boneRefs = {
    _rootJoint: React.useRef<THREE.Bone>(null),
    root_00: React.useRef<THREE.Bone>(null),
  }

  // Expose bone refs via useImperativeHandle
  React.useImperativeHandle(
    ref,
    () => ({
      _rootJoint: boneRefs._rootJoint.current,
      root_00: boneRefs.root_00.current,

      updateMatrixWorld: () => {
        if (group.current) {
          group.current.updateMatrixWorld(true)
        }
      },
    }),
    [],
  )
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[0, -1.571, 0]} scale={3}>
          <group rotation={[-1.57, 0, 0]} scale={247.269}>
            <primitive object={nodes._rootJoint} ref={boneRefs._rootJoint}>
              <primitive object={nodes.root_00} ref={boneRefs.root_00} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
            </primitive>
            <skinnedMesh geometry={nodes.Object_12.geometry} material={materials.Purple_Emis} skeleton={nodes.Object_12.skeleton} />
            <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.ps2_ns_shared_tv_blade} skeleton={nodes.Object_8.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
})

useGLTF.preload('/assets/models/weapons/AlienBlade.glb')
