/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 /Users/luis/GithubProjects/CaveGame/my-three-app/public/assets/models/monsters/ragno_monster.glb --output src/components/Monsters/ragno_monsterModel.tsx --types --bones --public-path /assets/models/monsters 
Author: Hobu (https://sketchfab.com/Hobu_Coffee)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ragno-monster-2e1a422e6f0048f98a786ceecac423d7
Title: Ragno (Monster)
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'Esqueleto|EsqueletoAction'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_12: THREE.SkinnedMesh
    Object_14: THREE.SkinnedMesh
    Object_16: THREE.SkinnedMesh
    Object_18: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
    Bone_00: THREE.Bone
    Bone001_01: THREE.Bone
    Bone002_02: THREE.Bone
    Bone003_03: THREE.Bone
    Bone003_end_040: THREE.Bone
    Bone005_04: THREE.Bone
    Bone006_05: THREE.Bone
    Bone007_06: THREE.Bone
    Bone008_07: THREE.Bone
    Bone009_08: THREE.Bone
    Bone009_end_041: THREE.Bone
    Bone011_09: THREE.Bone
    Bone012_010: THREE.Bone
    Bone013_011: THREE.Bone
    Bone014_012: THREE.Bone
    Bone015_013: THREE.Bone
    Bone015_end_042: THREE.Bone
    Bone017_014: THREE.Bone
    Bone018_015: THREE.Bone
    Bone019_016: THREE.Bone
    Bone020_017: THREE.Bone
    Bone021_018: THREE.Bone
    Bone021_end_043: THREE.Bone
    Bone023_019: THREE.Bone
    Bone024_020: THREE.Bone
    Bone025_021: THREE.Bone
    Bone026_022: THREE.Bone
    Bone027_023: THREE.Bone
    Bone027_end_044: THREE.Bone
    Bone004_024: THREE.Bone
    Bone029_025: THREE.Bone
    Bone030_026: THREE.Bone
    Bone031_027: THREE.Bone
    Bone031_end_045: THREE.Bone
    Bone032_028: THREE.Bone
    Bone033_029: THREE.Bone
    Bone034_030: THREE.Bone
    Bone034_end_046: THREE.Bone
    Bone010_031: THREE.Bone
    Bone010_end_047: THREE.Bone
    Bone016_032: THREE.Bone
    Bone016_end_048: THREE.Bone
    Bone022_033: THREE.Bone
    Bone022_end_049: THREE.Bone
    Bone028_034: THREE.Bone
    Bone028_end_050: THREE.Bone
    Bone035_035: THREE.Bone
    Bone035_end_051: THREE.Bone
    Bone037_036: THREE.Bone
    Bone037_end_052: THREE.Bone
    Bone038_037: THREE.Bone
    Bone038_end_053: THREE.Bone
    Bone036_038: THREE.Bone
    Bone036_end_054: THREE.Bone
    Bone039_039: THREE.Bone
    Bone039_end_055: THREE.Bone
  }
  materials: {
    ayez: THREE.MeshStandardMaterial
    Hair: THREE.MeshStandardMaterial
    Head: THREE.MeshStandardMaterial
    Body: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type BoneRefs = {
  _rootJoint: THREE.Bone | null
  Bone_00: THREE.Bone | null
  Bone001_01: THREE.Bone | null
  Bone002_02: THREE.Bone | null
  Bone003_03: THREE.Bone | null
  Bone003_end_040: THREE.Bone | null
  Bone005_04: THREE.Bone | null
  Bone006_05: THREE.Bone | null
  Bone007_06: THREE.Bone | null
  Bone008_07: THREE.Bone | null
  Bone009_08: THREE.Bone | null
  Bone009_end_041: THREE.Bone | null
  Bone011_09: THREE.Bone | null
  Bone012_010: THREE.Bone | null
  Bone013_011: THREE.Bone | null
  Bone014_012: THREE.Bone | null
  Bone015_013: THREE.Bone | null
  Bone015_end_042: THREE.Bone | null
  Bone017_014: THREE.Bone | null
  Bone018_015: THREE.Bone | null
  Bone019_016: THREE.Bone | null
  Bone020_017: THREE.Bone | null
  Bone021_018: THREE.Bone | null
  Bone021_end_043: THREE.Bone | null
  Bone023_019: THREE.Bone | null
  Bone024_020: THREE.Bone | null
  Bone025_021: THREE.Bone | null
  Bone026_022: THREE.Bone | null
  Bone027_023: THREE.Bone | null
  Bone027_end_044: THREE.Bone | null
  Bone004_024: THREE.Bone | null
  Bone029_025: THREE.Bone | null
  Bone030_026: THREE.Bone | null
  Bone031_027: THREE.Bone | null
  Bone031_end_045: THREE.Bone | null
  Bone032_028: THREE.Bone | null
  Bone033_029: THREE.Bone | null
  Bone034_030: THREE.Bone | null
  Bone034_end_046: THREE.Bone | null
  Bone010_031: THREE.Bone | null
  Bone010_end_047: THREE.Bone | null
  Bone016_032: THREE.Bone | null
  Bone016_end_048: THREE.Bone | null
  Bone022_033: THREE.Bone | null
  Bone022_end_049: THREE.Bone | null
  Bone028_034: THREE.Bone | null
  Bone028_end_050: THREE.Bone | null
  Bone035_035: THREE.Bone | null
  Bone035_end_051: THREE.Bone | null
  Bone037_036: THREE.Bone | null
  Bone037_end_052: THREE.Bone | null
  Bone038_037: THREE.Bone | null
  Bone038_end_053: THREE.Bone | null
  Bone036_038: THREE.Bone | null
  Bone036_end_054: THREE.Bone | null
  Bone039_039: THREE.Bone | null
  Bone039_end_055: THREE.Bone | null
  actions: any
  updateMatrixWorld: () => void
}

export default React.forwardRef<any, React.ComponentProps<'group'>>((props, ref) => {
  const group = React.useRef<THREE.Group>(null!)
  const { scene, animations } = useGLTF('/assets/models/monsters/ragno_monster.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)

  // Create refs for each bone
  const boneRefs = {
    _rootJoint: React.useRef<THREE.Bone>(null),
    Bone_00: React.useRef<THREE.Bone>(null),
    Bone001_01: React.useRef<THREE.Bone>(null),
    Bone002_02: React.useRef<THREE.Bone>(null),
    Bone003_03: React.useRef<THREE.Bone>(null),
    Bone003_end_040: React.useRef<THREE.Bone>(null),
    Bone005_04: React.useRef<THREE.Bone>(null),
    Bone006_05: React.useRef<THREE.Bone>(null),
    Bone007_06: React.useRef<THREE.Bone>(null),
    Bone008_07: React.useRef<THREE.Bone>(null),
    Bone009_08: React.useRef<THREE.Bone>(null),
    Bone009_end_041: React.useRef<THREE.Bone>(null),
    Bone011_09: React.useRef<THREE.Bone>(null),
    Bone012_010: React.useRef<THREE.Bone>(null),
    Bone013_011: React.useRef<THREE.Bone>(null),
    Bone014_012: React.useRef<THREE.Bone>(null),
    Bone015_013: React.useRef<THREE.Bone>(null),
    Bone015_end_042: React.useRef<THREE.Bone>(null),
    Bone017_014: React.useRef<THREE.Bone>(null),
    Bone018_015: React.useRef<THREE.Bone>(null),
    Bone019_016: React.useRef<THREE.Bone>(null),
    Bone020_017: React.useRef<THREE.Bone>(null),
    Bone021_018: React.useRef<THREE.Bone>(null),
    Bone021_end_043: React.useRef<THREE.Bone>(null),
    Bone023_019: React.useRef<THREE.Bone>(null),
    Bone024_020: React.useRef<THREE.Bone>(null),
    Bone025_021: React.useRef<THREE.Bone>(null),
    Bone026_022: React.useRef<THREE.Bone>(null),
    Bone027_023: React.useRef<THREE.Bone>(null),
    Bone027_end_044: React.useRef<THREE.Bone>(null),
    Bone004_024: React.useRef<THREE.Bone>(null),
    Bone029_025: React.useRef<THREE.Bone>(null),
    Bone030_026: React.useRef<THREE.Bone>(null),
    Bone031_027: React.useRef<THREE.Bone>(null),
    Bone031_end_045: React.useRef<THREE.Bone>(null),
    Bone032_028: React.useRef<THREE.Bone>(null),
    Bone033_029: React.useRef<THREE.Bone>(null),
    Bone034_030: React.useRef<THREE.Bone>(null),
    Bone034_end_046: React.useRef<THREE.Bone>(null),
    Bone010_031: React.useRef<THREE.Bone>(null),
    Bone010_end_047: React.useRef<THREE.Bone>(null),
    Bone016_032: React.useRef<THREE.Bone>(null),
    Bone016_end_048: React.useRef<THREE.Bone>(null),
    Bone022_033: React.useRef<THREE.Bone>(null),
    Bone022_end_049: React.useRef<THREE.Bone>(null),
    Bone028_034: React.useRef<THREE.Bone>(null),
    Bone028_end_050: React.useRef<THREE.Bone>(null),
    Bone035_035: React.useRef<THREE.Bone>(null),
    Bone035_end_051: React.useRef<THREE.Bone>(null),
    Bone037_036: React.useRef<THREE.Bone>(null),
    Bone037_end_052: React.useRef<THREE.Bone>(null),
    Bone038_037: React.useRef<THREE.Bone>(null),
    Bone038_end_053: React.useRef<THREE.Bone>(null),
    Bone036_038: React.useRef<THREE.Bone>(null),
    Bone036_end_054: React.useRef<THREE.Bone>(null),
    Bone039_039: React.useRef<THREE.Bone>(null),
    Bone039_end_055: React.useRef<THREE.Bone>(null),
  }

  // Expose bone refs via useImperativeHandle
  React.useImperativeHandle(
    ref,
    () => ({
      _rootJoint: boneRefs._rootJoint.current,
      Bone_00: boneRefs.Bone_00.current,
      Bone001_01: boneRefs.Bone001_01.current,
      Bone002_02: boneRefs.Bone002_02.current,
      Bone003_03: boneRefs.Bone003_03.current,
      Bone003_end_040: boneRefs.Bone003_end_040.current,
      Bone005_04: boneRefs.Bone005_04.current,
      Bone006_05: boneRefs.Bone006_05.current,
      Bone007_06: boneRefs.Bone007_06.current,
      Bone008_07: boneRefs.Bone008_07.current,
      Bone009_08: boneRefs.Bone009_08.current,
      Bone009_end_041: boneRefs.Bone009_end_041.current,
      Bone011_09: boneRefs.Bone011_09.current,
      Bone012_010: boneRefs.Bone012_010.current,
      Bone013_011: boneRefs.Bone013_011.current,
      Bone014_012: boneRefs.Bone014_012.current,
      Bone015_013: boneRefs.Bone015_013.current,
      Bone015_end_042: boneRefs.Bone015_end_042.current,
      Bone017_014: boneRefs.Bone017_014.current,
      Bone018_015: boneRefs.Bone018_015.current,
      Bone019_016: boneRefs.Bone019_016.current,
      Bone020_017: boneRefs.Bone020_017.current,
      Bone021_018: boneRefs.Bone021_018.current,
      Bone021_end_043: boneRefs.Bone021_end_043.current,
      Bone023_019: boneRefs.Bone023_019.current,
      Bone024_020: boneRefs.Bone024_020.current,
      Bone025_021: boneRefs.Bone025_021.current,
      Bone026_022: boneRefs.Bone026_022.current,
      Bone027_023: boneRefs.Bone027_023.current,
      Bone027_end_044: boneRefs.Bone027_end_044.current,
      Bone004_024: boneRefs.Bone004_024.current,
      Bone029_025: boneRefs.Bone029_025.current,
      Bone030_026: boneRefs.Bone030_026.current,
      Bone031_027: boneRefs.Bone031_027.current,
      Bone031_end_045: boneRefs.Bone031_end_045.current,
      Bone032_028: boneRefs.Bone032_028.current,
      Bone033_029: boneRefs.Bone033_029.current,
      Bone034_030: boneRefs.Bone034_030.current,
      Bone034_end_046: boneRefs.Bone034_end_046.current,
      Bone010_031: boneRefs.Bone010_031.current,
      Bone010_end_047: boneRefs.Bone010_end_047.current,
      Bone016_032: boneRefs.Bone016_032.current,
      Bone016_end_048: boneRefs.Bone016_end_048.current,
      Bone022_033: boneRefs.Bone022_033.current,
      Bone022_end_049: boneRefs.Bone022_end_049.current,
      Bone028_034: boneRefs.Bone028_034.current,
      Bone028_end_050: boneRefs.Bone028_end_050.current,
      Bone035_035: boneRefs.Bone035_035.current,
      Bone035_end_051: boneRefs.Bone035_end_051.current,
      Bone037_036: boneRefs.Bone037_036.current,
      Bone037_end_052: boneRefs.Bone037_end_052.current,
      Bone038_037: boneRefs.Bone038_037.current,
      Bone038_end_053: boneRefs.Bone038_end_053.current,
      Bone036_038: boneRefs.Bone036_038.current,
      Bone036_end_054: boneRefs.Bone036_end_054.current,
      Bone039_039: boneRefs.Bone039_039.current,
      Bone039_end_055: boneRefs.Bone039_end_055.current,
      actions,
      updateMatrixWorld: () => {
        if (group.current) {
          group.current.updateMatrixWorld(true)
        }
      },
    }),
    [actions],
  )
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.562}>
          <group name="3d6634cbb12e428299fc02ca86747eb6fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Body" position={[0, 241.839, 0]} scale={0.111}>
                  <group name="Head_" position={[-0.406, 155.344, 151.016]} rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Esfera" position={[0, 162.624, 154.366]} scale={0.114} />
                    <group name="Hair" position={[0.016, 143.58, 121.276]} rotation={[Math.PI / 2, 0, 0]} scale={0.051} />
                  </group>
                </group>
                <group name="Esqueleto" position={[0, 162.624, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_9">
                    <primitive object={nodes._rootJoint} ref={boneRefs._rootJoint} name="_rootJoint">
                      <primitive object={nodes.Bone_00} ref={boneRefs.Bone_00} name="Bone_00" position={[0, 0.193, 0.469]} rotation={[-3.028, 0, 0]}>
                        <primitive object={nodes.Bone001_01} ref={boneRefs.Bone001_01} name="Bone001_01" position={[0, 0.31, 0]} rotation={[0.909, 0, 0]}>
                          <primitive object={nodes.Bone002_02} ref={boneRefs.Bone002_02} name="Bone002_02" position={[0, 0.415, 0]} rotation={[-0.124, 0, 0]}>
                            <primitive object={nodes.Bone003_03} ref={boneRefs.Bone003_03} name="Bone003_03" position={[0, 0.318, 0]} rotation={[-0.92, 0, 0]}>
                              <primitive object={nodes.Bone003_end_040} ref={boneRefs.Bone003_end_040} name="Bone003_end_040" position={[0, 0.423, 0]} />
                            </primitive>
                          </primitive>
                        </primitive>
                        <primitive object={nodes.Bone005_04} ref={boneRefs.Bone005_04} name="Bone005_04" position={[0.168, 0.283, -0.075]} rotation={[-1.629, -0.054, -0.728]}>
                          <primitive object={nodes.Bone006_05} ref={boneRefs.Bone006_05} name="Bone006_05" position={[0, 0.339, 0]} rotation={[-0.077, 0.01, -0.264]}>
                            <primitive object={nodes.Bone007_06} ref={boneRefs.Bone007_06} name="Bone007_06" position={[0, 0.346, 0]} rotation={[-0.006, -0.001, 0.365]}>
                              <primitive object={nodes.Bone008_07} ref={boneRefs.Bone008_07} name="Bone008_07" position={[0, 0.751, 0]} rotation={[0.017, -0.014, -1.356]}>
                                <primitive object={nodes.Bone009_08} ref={boneRefs.Bone009_08} name="Bone009_08" position={[0, 0.332, 0]} rotation={[0.009, -0.002, -0.527]}>
                                  <primitive object={nodes.Bone009_end_041} ref={boneRefs.Bone009_end_041} name="Bone009_end_041" position={[0, 0.336, 0]} />
                                </primitive>
                              </primitive>
                            </primitive>
                          </primitive>
                        </primitive>
                        <primitive object={nodes.Bone011_09} ref={boneRefs.Bone011_09} name="Bone011_09" position={[0.112, 0.097, -0.054]} rotation={[-2.079, 0.321, -0.632]}>
                          <primitive object={nodes.Bone012_010} ref={boneRefs.Bone012_010} name="Bone012_010" position={[0, 0.412, 0]} rotation={[-0.661, 0.121, 0.265]}>
                            <primitive object={nodes.Bone013_011} ref={boneRefs.Bone013_011} name="Bone013_011" position={[0, 0.36, 0]} rotation={[0.415, -0.4, 0.34]}>
                              <primitive object={nodes.Bone014_012} ref={boneRefs.Bone014_012} name="Bone014_012" position={[0, 0.782, 0]} rotation={[0.977, 0.864, -2.335]}>
                                <primitive object={nodes.Bone015_013} ref={boneRefs.Bone015_013} name="Bone015_013" position={[0, 0.282, 0]} rotation={[0.29, 1.001, 0.006]}>
                                  <primitive object={nodes.Bone015_end_042} ref={boneRefs.Bone015_end_042} name="Bone015_end_042" position={[0, 0.325, 0]} />
                                </primitive>
                              </primitive>
                            </primitive>
                          </primitive>
                        </primitive>
                        <primitive object={nodes.Bone017_014} ref={boneRefs.Bone017_014} name="Bone017_014" position={[-0.168, 0.283, -0.075]} rotation={[-1.53, -0.05, 0.728]}>
                          <primitive object={nodes.Bone018_015} ref={boneRefs.Bone018_015} name="Bone018_015" position={[0, 0.339, 0]} rotation={[-0.087, 0.155, 0.276]}>
                            <primitive object={nodes.Bone019_016} ref={boneRefs.Bone019_016} name="Bone019_016" position={[0, 0.346, 0]} rotation={[0.006, -0.001, -0.365]}>
                              <primitive object={nodes.Bone020_017} ref={boneRefs.Bone020_017} name="Bone020_017" position={[0, 0.751, 0]} rotation={[-0.017, -0.014, 1.356]}>
                                <primitive object={nodes.Bone021_018} ref={boneRefs.Bone021_018} name="Bone021_018" position={[0, 0.332, 0]} rotation={[-0.009, -0.002, 0.527]}>
                                  <primitive object={nodes.Bone021_end_043} ref={boneRefs.Bone021_end_043} name="Bone021_end_043" position={[0, 0.336, 0]} />
                                </primitive>
                              </primitive>
                            </primitive>
                          </primitive>
                        </primitive>
                        <primitive object={nodes.Bone023_019} ref={boneRefs.Bone023_019} name="Bone023_019" position={[-0.112, 0.097, -0.054]} rotation={[-2.515, 0.322, 0.614]}>
                          <primitive object={nodes.Bone024_020} ref={boneRefs.Bone024_020} name="Bone024_020" position={[0, 0.412, 0]} rotation={[0.078, 0.486, -0.708]}>
                            <primitive object={nodes.Bone025_021} ref={boneRefs.Bone025_021} name="Bone025_021" position={[0, 0.36, 0]} rotation={[0.459, -0.437, 0.253]}>
                              <primitive object={nodes.Bone026_022} ref={boneRefs.Bone026_022} name="Bone026_022" position={[0, 0.782, 0]} rotation={[1.608, 1.035, -3.106]}>
                                <primitive object={nodes.Bone027_023} ref={boneRefs.Bone027_023} name="Bone027_023" position={[0, 0.282, 0]} rotation={[0.374, 1.071, -0.57]}>
                                  <primitive object={nodes.Bone027_end_044} ref={boneRefs.Bone027_end_044} name="Bone027_end_044" position={[0, 0.325, 0]} />
                                </primitive>
                              </primitive>
                            </primitive>
                          </primitive>
                        </primitive>
                      </primitive>
                      <primitive object={nodes.Bone004_024} ref={boneRefs.Bone004_024} name="Bone004_024" position={[0, -0.952, -0.159]} rotation={[3.107, 0, 0]}>
                        <primitive object={nodes.Bone029_025} ref={boneRefs.Bone029_025} name="Bone029_025" position={[0.032, 0.327, -0.6]} rotation={[-1.536, 0, -2.255]}>
                          <primitive object={nodes.Bone030_026} ref={boneRefs.Bone030_026} name="Bone030_026" position={[0, 0.281, 0]} rotation={[0, 0, -0.875]}>
                            <primitive object={nodes.Bone031_027} ref={boneRefs.Bone031_027} name="Bone031_027" position={[0, 0.481, 0]} rotation={[0, 0, -0.083]}>
                              <primitive object={nodes.Bone031_end_045} ref={boneRefs.Bone031_end_045} name="Bone031_end_045" position={[0, 0.717, 0]} />
                            </primitive>
                          </primitive>
                        </primitive>
                        <primitive object={nodes.Bone032_028} ref={boneRefs.Bone032_028} name="Bone032_028" position={[-0.032, 0.327, -0.6]} rotation={[-1.536, 0, 2.255]}>
                          <primitive object={nodes.Bone033_029} ref={boneRefs.Bone033_029} name="Bone033_029" position={[0, 0.281, 0]} rotation={[0, 0, 0.875]}>
                            <primitive object={nodes.Bone034_030} ref={boneRefs.Bone034_030} name="Bone034_030" position={[0, 0.481, 0]} rotation={[0, 0, 0.083]}>
                              <primitive object={nodes.Bone034_end_046} ref={boneRefs.Bone034_end_046} name="Bone034_end_046" position={[0, 0.717, 0]} />
                            </primitive>
                          </primitive>
                        </primitive>
                      </primitive>
                      <primitive object={nodes.Bone010_031} ref={boneRefs.Bone010_031} name="Bone010_031" position={[1.626, -0.124, 1.155]} rotation={[1.571, -0.017, 3.139]}>
                        <primitive object={nodes.Bone010_end_047} ref={boneRefs.Bone010_end_047} name="Bone010_end_047" position={[0, 2.56, 0]} />
                      </primitive>
                      <primitive object={nodes.Bone016_032} ref={boneRefs.Bone016_032} name="Bone016_032" position={[0.578, 1.517, 1.237]} rotation={[1.578, -0.002, 3.139]}>
                        <primitive object={nodes.Bone016_end_048} ref={boneRefs.Bone016_end_048} name="Bone016_end_048" position={[0, 2.716, 0]} />
                      </primitive>
                      <primitive object={nodes.Bone022_033} ref={boneRefs.Bone022_033} name="Bone022_033" position={[-1.626, -0.124, 1.155]} rotation={[1.571, -0.017, -3.139]}>
                        <primitive object={nodes.Bone022_end_049} ref={boneRefs.Bone022_end_049} name="Bone022_end_049" position={[0, 2.56, 0]} />
                      </primitive>
                      <primitive object={nodes.Bone028_034} ref={boneRefs.Bone028_034} name="Bone028_034" position={[-0.578, 1.517, 1.237]} rotation={[1.578, -0.002, -3.139]}>
                        <primitive object={nodes.Bone028_end_050} ref={boneRefs.Bone028_end_050} name="Bone028_end_050" position={[0, 2.716, 0]} />
                      </primitive>
                      <primitive object={nodes.Bone035_035} ref={boneRefs.Bone035_035} name="Bone035_035" position={[1.153, -0.124, 1.775]} rotation={[1.573, 0.017, -0.109]}>
                        <primitive object={nodes.Bone035_end_051} ref={boneRefs.Bone035_end_051} name="Bone035_end_051" position={[0, 0.499, 0]} />
                      </primitive>
                      <primitive object={nodes.Bone037_036} ref={boneRefs.Bone037_036} name="Bone037_036" position={[0.426, 1.115, 1.729]} rotation={[-1.701, 1.23, -Math.PI]}>
                        <primitive object={nodes.Bone037_end_052} ref={boneRefs.Bone037_end_052} name="Bone037_end_052" position={[0, 0.461, 0]} />
                      </primitive>
                      <primitive object={nodes.Bone038_037} ref={boneRefs.Bone038_037} name="Bone038_037" position={[-0.426, 1.115, 1.729]} rotation={[-1.701, 0.805, -Math.PI]}>
                        <primitive object={nodes.Bone038_end_053} ref={boneRefs.Bone038_end_053} name="Bone038_end_053" position={[0, 0.461, 0]} />
                      </primitive>
                      <primitive object={nodes.Bone036_038} ref={boneRefs.Bone036_038} name="Bone036_038" position={[-1.153, -0.124, 1.775]} rotation={[1.569, 0.017, 0.109]}>
                        <primitive object={nodes.Bone036_end_054} ref={boneRefs.Bone036_end_054} name="Bone036_end_054" position={[0, 0.499, 0]} />
                      </primitive>
                      <primitive object={nodes.Bone039_039} ref={boneRefs.Bone039_039} name="Bone039_039" position={[0, -0.43, -0.312]} rotation={[-1.117, 0, 0]}>
                        <primitive object={nodes.Bone039_end_055} ref={boneRefs.Bone039_end_055} name="Bone039_end_055" position={[0, 0.503, 0]} />
                      </primitive>
                    </primitive>
                    <group name="Object_11" position={[0, 162.624, 154.366]} scale={0.114} />
                    <group name="Object_13" position={[0.016, 143.58, 121.276]} rotation={[Math.PI / 2, 0, 0]} scale={0.051} />
                    <group name="Object_15" position={[-0.406, 155.344, 151.016]} rotation={[Math.PI / 2, 0, 0]} />
                    <group name="Object_17" position={[0, 241.839, 0]} scale={0.111} />
                    <skinnedMesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.ayez} skeleton={nodes.Object_12.skeleton} />
                    <skinnedMesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.Hair} skeleton={nodes.Object_14.skeleton} />
                    <skinnedMesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.Head} skeleton={nodes.Object_16.skeleton} />
                    <skinnedMesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.Body} skeleton={nodes.Object_18.skeleton} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
})

useGLTF.preload('/assets/models/monsters/ragno_monster.glb')
