/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 /Users/luis/GithubProjects/CaveGame/my-three-app/public/assets/models/monsters/void-spider/source/voided_spider.glb --output src/components/Monsters/voided_spiderModel.tsx --types --bones --public-path /assets/models/monsters/void-spider/source 
Author: RedVoid_ (https://sketchfab.com/RedVoid_)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/voided-spider-08013f2480d949a18642507cf6d96693
Title: Voided Spider
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'idle' | 'capture' | 'running' | 'running_wall' | 'running_ceiling' | 'sprinting' | 'attack_L' | 'attack_R' | 'attack_jaw' | 'attack_inner_jaw' | 'hit'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_19_1: THREE.Mesh
    Object_21_1: THREE.Mesh
    Object_25_1: THREE.Mesh
    Object_27_1: THREE.Mesh
    Object_31_1: THREE.Mesh
    Object_33_1: THREE.Mesh
    Object_37_1: THREE.Mesh
    Object_39_1: THREE.Mesh
    Object_41_1: THREE.Mesh
    Object_43_1: THREE.Mesh
    Object_45: THREE.Mesh
    Object_47: THREE.Mesh
    Object_49: THREE.Mesh
    Object_51: THREE.Mesh
    Object_53: THREE.Mesh
    Object_55: THREE.Mesh
    Object_58: THREE.Mesh
    Object_85: THREE.Mesh
    Object_87: THREE.Mesh
    Object_91: THREE.Mesh
    Object_93: THREE.Mesh
    Object_98: THREE.Mesh
    Object_100: THREE.Mesh
    Object_102: THREE.Mesh
    Object_107: THREE.Mesh
    Object_109: THREE.Mesh
    Object_111: THREE.Mesh
    Object_119: THREE.Mesh
    Object_122: THREE.Mesh
    Object_124: THREE.Mesh
    Object_127: THREE.Mesh
    Object_129: THREE.Mesh
    Object_132: THREE.Mesh
    Object_135: THREE.Mesh
    Object_138: THREE.Mesh
    Object_140: THREE.Mesh
    Object_142: THREE.Mesh
    Object_149: THREE.Mesh
    Object_151: THREE.Mesh
    Object_153: THREE.Mesh
    Object_155: THREE.Mesh
    Object_157: THREE.Mesh
    Object_159: THREE.Mesh
    Object_161: THREE.Mesh
    Object_163: THREE.Mesh
    Object_170: THREE.Mesh
    Object_172: THREE.Mesh
    Object_174: THREE.Mesh
    Object_176: THREE.Mesh
    Object_178: THREE.Mesh
    Object_180: THREE.Mesh
    Object_182: THREE.Mesh
    Object_184: THREE.Mesh
    Object_62: THREE.Mesh
    Object_65: THREE.Mesh
    Object_68: THREE.Mesh
    Object_72: THREE.Mesh
    Object_75: THREE.Mesh
    Object_78: THREE.Mesh
    Object_81: THREE.Mesh
    Object_186: THREE.Mesh
    Object_188: THREE.Mesh
    Object_190: THREE.Mesh
    Object_192: THREE.Mesh
    Object_200: THREE.Mesh
    Object_202: THREE.Mesh
    Object_204: THREE.Mesh
    Object_206: THREE.Mesh
    Object_208: THREE.Mesh
    Object_210: THREE.Mesh
    Object_212: THREE.Mesh
    Object_214: THREE.Mesh
    Object_216: THREE.Mesh
    Object_218: THREE.Mesh
    Object_220: THREE.Mesh
    Object_222: THREE.Mesh
    Object_224: THREE.Mesh
    Object_230: THREE.Mesh
    Object_232: THREE.Mesh
    Object_234: THREE.Mesh
    Object_236: THREE.Mesh
    Object_238: THREE.Mesh
    Object_240: THREE.Mesh
    Object_242: THREE.Mesh
    Object_244: THREE.Mesh
    Object_246: THREE.Mesh
    Object_248: THREE.Mesh
    Object_250: THREE.Mesh
    Object_252: THREE.Mesh
    Object_254: THREE.Mesh
    Object_260: THREE.Mesh
    Object_262: THREE.Mesh
    Object_264: THREE.Mesh
    Object_266: THREE.Mesh
    Object_268: THREE.Mesh
    Object_270: THREE.Mesh
    Object_272: THREE.Mesh
    Object_274: THREE.Mesh
    Object_276: THREE.Mesh
    Object_278: THREE.Mesh
    Object_280: THREE.Mesh
    Object_282: THREE.Mesh
    Object_284: THREE.Mesh
    Object_290: THREE.Mesh
    Object_292: THREE.Mesh
    Object_294: THREE.Mesh
    Object_296: THREE.Mesh
    Object_298: THREE.Mesh
    Object_300: THREE.Mesh
    Object_302: THREE.Mesh
    Object_304: THREE.Mesh
    Object_306: THREE.Mesh
    Object_308: THREE.Mesh
    Object_310: THREE.Mesh
    Object_312: THREE.Mesh
    Object_314: THREE.Mesh
    Object_321: THREE.Mesh
    Object_323: THREE.Mesh
    Object_325: THREE.Mesh
    Object_327: THREE.Mesh
    Object_329: THREE.Mesh
    Object_331: THREE.Mesh
    Object_333: THREE.Mesh
    Object_335: THREE.Mesh
    Object_337: THREE.Mesh
    Object_339: THREE.Mesh
    Object_341: THREE.Mesh
    Object_343: THREE.Mesh
    Object_345: THREE.Mesh
    Object_351: THREE.Mesh
    Object_353: THREE.Mesh
    Object_355: THREE.Mesh
    Object_357: THREE.Mesh
    Object_359: THREE.Mesh
    Object_361: THREE.Mesh
    Object_363: THREE.Mesh
    Object_365: THREE.Mesh
    Object_367: THREE.Mesh
    Object_369: THREE.Mesh
    Object_371: THREE.Mesh
    Object_373: THREE.Mesh
    Object_375: THREE.Mesh
    Object_381: THREE.Mesh
    Object_383: THREE.Mesh
    Object_385: THREE.Mesh
    Object_387: THREE.Mesh
    Object_389: THREE.Mesh
    Object_391: THREE.Mesh
    Object_393: THREE.Mesh
    Object_395: THREE.Mesh
    Object_397: THREE.Mesh
    Object_399: THREE.Mesh
    Object_401: THREE.Mesh
    Object_403: THREE.Mesh
    Object_405: THREE.Mesh
    Object_411: THREE.Mesh
    Object_413: THREE.Mesh
    Object_415: THREE.Mesh
    Object_417: THREE.Mesh
    Object_419: THREE.Mesh
    Object_421: THREE.Mesh
    Object_423: THREE.Mesh
    Object_425: THREE.Mesh
    Object_427: THREE.Mesh
    Object_429: THREE.Mesh
    Object_431: THREE.Mesh
    Object_433: THREE.Mesh
    Object_435: THREE.Mesh
  }
  materials: {
    material_0: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: React.ComponentProps<'group'>) {
  const group = React.useRef<THREE.Group>(null!)
  const { nodes, materials, animations } = useGLTF('/assets/models/monsters/void-spider/source/voided_spider.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.603}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="_264">
                <group name="ALL_263" position={[0, 0.438, 0.063]}>
                  <group name="Root_262">
                    <group name="afj_122">
                      <group name="Body_121">
                        <group name="inner_mouth_31" position={[0, -0.125, -0.363]}>
                          <group name="inner_mouth2_29" position={[0, 0, -0.125]}>
                            <group name="inner_mouth3_27" position={[0, 0, -0.125]}>
                              <group name="inner_mouth4_25" position={[0, 0, -0.125]}>
                                <group name="inner_mouth5_23" position={[0, 0, -0.125]}>
                                  <group name="inner_mouth6_21" position={[0, 0, -0.125]}>
                                    <group name="inner_mouth7_19" position={[0, 0, -0.125]}>
                                      <group name="inner_mouth8_17" position={[0, 0, -0.125]}>
                                        <group name="inner_jaw_T_L_3" position={[-0.063, 0.063, -0.094]} rotation={[0, 0, -Math.PI / 4]}>
                                          <group name="inner_jaw_T_L2_1" position={[-0.094, 0, 0]}>
                                            <group name="cube_0" position={[0.094, -0.375, 0.719]}>
                                              <mesh name="Object_19_1" geometry={nodes.Object_19_1.geometry} material={materials.material_0} />
                                            </group>
                                          </group>
                                          <group name="cube_2" position={[0.063, -0.375, 0.719]}>
                                            <mesh name="Object_21_1" geometry={nodes.Object_21_1.geometry} material={materials.material_0} />
                                          </group>
                                        </group>
                                        <group name="inner_jaw_B_L_7" position={[-0.063, -0.063, -0.094]} rotation={[0, 0, -Math.PI / 4]}>
                                          <group name="inner_jaw_B_L2_5" position={[0, -0.094, 0]}>
                                            <group name="cube_4" position={[0.063, -0.344, 0.719]}>
                                              <mesh name="Object_25_1" geometry={nodes.Object_25_1.geometry} material={materials.material_0} />
                                            </group>
                                          </group>
                                          <group name="cube_6" position={[0.063, -0.375, 0.719]}>
                                            <mesh name="Object_27_1" geometry={nodes.Object_27_1.geometry} material={materials.material_0} />
                                          </group>
                                        </group>
                                        <group name="inner_jaw_B_R_11" position={[0.063, -0.063, -0.094]} rotation={[0, 0, -Math.PI / 4]}>
                                          <group name="inner_jaw_B_R2_9" position={[0.094, 0, 0]}>
                                            <group name="cube_8" position={[0.031, -0.375, 0.719]}>
                                              <mesh name="Object_31_1" geometry={nodes.Object_31_1.geometry} material={materials.material_0} />
                                            </group>
                                          </group>
                                          <group name="cube_10" position={[0.063, -0.375, 0.719]}>
                                            <mesh name="Object_33_1" geometry={nodes.Object_33_1.geometry} material={materials.material_0} />
                                          </group>
                                        </group>
                                        <group name="inner_jaw_T_R_15" position={[0.063, 0.063, -0.094]} rotation={[0, 0, -Math.PI / 4]}>
                                          <group name="inner_jaw_T_R2_13" position={[0, 0.094, 0]}>
                                            <group name="cube_12" position={[0.063, -0.406, 0.719]}>
                                              <mesh name="Object_37_1" geometry={nodes.Object_37_1.geometry} material={materials.material_0} />
                                            </group>
                                          </group>
                                          <group name="cube_14" position={[0.063, -0.375, 0.719]}>
                                            <mesh name="Object_39_1" geometry={nodes.Object_39_1.geometry} material={materials.material_0} />
                                          </group>
                                        </group>
                                        <group name="cube_16" position={[0, -0.313, 0.563]}>
                                          <mesh name="Object_41_1" geometry={nodes.Object_41_1.geometry} material={materials.material_0} />
                                        </group>
                                      </group>
                                      <group name="cube_18" position={[0, 0, -0.063]} rotation={[0, 0, Math.PI / 4]}>
                                        <mesh name="Object_43_1" geometry={nodes.Object_43_1.geometry} material={materials.material_0} />
                                      </group>
                                    </group>
                                    <group name="cube_20" position={[0, 0, -0.063]} rotation={[0, 0, Math.PI / 4]}>
                                      <mesh name="Object_45" geometry={nodes.Object_45.geometry} material={materials.material_0} />
                                    </group>
                                  </group>
                                  <group name="cube_22" position={[0, 0, -0.063]} rotation={[0, 0, Math.PI / 4]}>
                                    <mesh name="Object_47" geometry={nodes.Object_47.geometry} material={materials.material_0} />
                                  </group>
                                </group>
                                <group name="cube_24" position={[0, 0, -0.063]} rotation={[0, 0, Math.PI / 4]}>
                                  <mesh name="Object_49" geometry={nodes.Object_49.geometry} material={materials.material_0} />
                                </group>
                              </group>
                              <group name="cube_26" position={[0, 0, -0.063]} rotation={[0, 0, Math.PI / 4]}>
                                <mesh name="Object_51" geometry={nodes.Object_51.geometry} material={materials.material_0} />
                              </group>
                            </group>
                            <group name="cube_28" position={[0, 0, -0.063]} rotation={[0, 0, Math.PI / 4]}>
                              <mesh name="Object_53" geometry={nodes.Object_53.geometry} material={materials.material_0} />
                            </group>
                          </group>
                          <group name="cube_30" position={[0, 0, -0.063]} rotation={[0, 0, Math.PI / 4]}>
                            <mesh name="Object_55" geometry={nodes.Object_55.geometry} material={materials.material_0} />
                          </group>
                        </group>
                        <group name="bone4_33" position={[0, 0.094, -0.578]}>
                          <group name="cube_32" position={[0, 0, 0.016]} rotation={[0, Math.PI / 4, 0]}>
                            <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.material_0} />
                          </group>
                        </group>
                        <group name="jaw_L_T_53" position={[-0.125, -0.031, -0.453]}>
                          <group name="jaw_L_T2_51" position={[0, -0.125, -0.094]}>
                            <group name="cube_50" position={[0, 0.156, 0.094]}>
                              <mesh name="Object_85" geometry={nodes.Object_85.geometry} material={materials.material_0} />
                            </group>
                          </group>
                          <group name="cube_52" position={[0, 0.031, 0]}>
                            <mesh name="Object_87" geometry={nodes.Object_87.geometry} material={materials.material_0} />
                          </group>
                        </group>
                        <group name="jaw_R_T_57" position={[0.125, -0.031, -0.453]}>
                          <group name="jaw_R_T2_55" position={[0, -0.125, -0.094]}>
                            <group name="cube_54" position={[-0.25, 0.156, 0.094]}>
                              <mesh name="Object_91" geometry={nodes.Object_91.geometry} material={materials.material_0} />
                            </group>
                          </group>
                          <group name="cube_56" position={[-0.125, 0.094, 0.688]}>
                            <mesh name="Object_93" geometry={nodes.Object_93.geometry} material={materials.material_0} />
                          </group>
                        </group>
                        <group name="jaw_L_B_63" position={[-0.125, -0.156, -0.313]}>
                          <group name="jaw_L_B2_61" position={[0, 0, -0.125]}>
                            <group name="jaw_L_B3_59" position={[0, 0.125, -0.031]}>
                              <group name="cube_58" position={[0, -0.156, -0.094]}>
                                <mesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials.material_0} />
                              </group>
                            </group>
                            <group name="cube_60" position={[0.125, 0.25, 0.688]}>
                              <mesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials.material_0} />
                            </group>
                          </group>
                          <group name="cube_62" position={[0.125, 0.188, 0.563]}>
                            <mesh name="Object_102" geometry={nodes.Object_102.geometry} material={materials.material_0} />
                          </group>
                        </group>
                        <group name="jaw_R_B_69" position={[0.125, -0.156, -0.313]}>
                          <group name="jaw_R_B2_67" position={[0, 0, -0.125]}>
                            <group name="jaw_R_B3_65" position={[0, 0.125, -0.031]}>
                              <group name="cube_64" position={[0, -0.156, -0.094]}>
                                <mesh name="Object_107" geometry={nodes.Object_107.geometry} material={materials.material_0} />
                              </group>
                            </group>
                            <group name="cube_66" position={[0.125, 0.25, 0.688]}>
                              <mesh name="Object_109" geometry={nodes.Object_109.geometry} material={materials.material_0} />
                            </group>
                          </group>
                          <group name="cube_68" position={[0.125, 0.188, 0.563]}>
                            <mesh name="Object_111" geometry={nodes.Object_111.geometry} material={materials.material_0} />
                          </group>
                        </group>
                        <group name="abdomen_90" position={[0, 0, 0.438]} rotation={[-0.175, 0, 0]}>
                          <group name="abdomen2_88" position={[0, 0.063, 0.063]} rotation={[0.175, 0, 0]}>
                            <group name="abdomen3_80" position={[0, 0, 0.563]} rotation={[0.262, 0, 0]}>
                              <group name="abdomen4_76" position={[0, -0.063, 0.188]} rotation={[Math.PI / 9, 0, 0]}>
                                <group name="abdomen5_74" position={[0, 0, 0.188]}>
                                  <group name="abdomen_L_71" position={[-0.063, 0, 0]}>
                                    <group name="cube_70" position={[0.063, 0, -1]}>
                                      <mesh name="Object_119" geometry={nodes.Object_119.geometry} material={materials.material_0} />
                                    </group>
                                  </group>
                                  <group name="abdomen_R_73" position={[0.063, 0, 0]}>
                                    <group name="cube_72" position={[-0.063, 0, -1]}>
                                      <mesh name="Object_122" geometry={nodes.Object_122.geometry} material={materials.material_0} />
                                    </group>
                                  </group>
                                </group>
                                <group name="cube_75" position={[0, 0, -0.813]} rotation={[0, 0, Math.PI / 4]}>
                                  <mesh name="Object_124" geometry={nodes.Object_124.geometry} material={materials.material_0} />
                                </group>
                              </group>
                              <group name="spikes_abdomen_center2_78" position={[0, 0.281, -0.125]}>
                                <group name="cube_77" position={[0, -0.281, 0.125]}>
                                  <mesh name="Object_127" geometry={nodes.Object_127.geometry} material={materials.material_0} />
                                </group>
                              </group>
                              <group name="cube_79" position={[0, -0.063, -0.625]} rotation={[0, 0, Math.PI / 4]}>
                                <mesh name="Object_129" geometry={nodes.Object_129.geometry} material={materials.material_0} />
                              </group>
                            </group>
                            <group name="spikes_abdomen_center_82" position={[0, 0.469, 0]}>
                              <group name="cube_81" position={[0, -0.469, 0]}>
                                <mesh name="Object_132" geometry={nodes.Object_132.geometry} material={materials.material_0} />
                              </group>
                            </group>
                            <group name="spikes_abdomen_L_84" position={[-0.125, 0.344, 0]}>
                              <group name="cube_83" rotation={[0, 0, 0.262]}>
                                <mesh name="Object_135" geometry={nodes.Object_135.geometry} material={materials.material_0} />
                              </group>
                            </group>
                            <group name="spikes_abdomen_R_86" position={[0.125, 0.344, 0]}>
                              <group name="cube_85" rotation={[0, 0, -0.262]}>
                                <mesh name="Object_138" geometry={nodes.Object_138.geometry} material={materials.material_0} />
                              </group>
                            </group>
                            <group name="cube_87" position={[0, -0.063, -0.063]} rotation={[0, 0, Math.PI / 4]}>
                              <mesh name="Object_140" geometry={nodes.Object_140.geometry} material={materials.material_0} />
                            </group>
                          </group>
                          <group name="cube_89" rotation={[0, 0, Math.PI / 4]}>
                            <mesh name="Object_142" geometry={nodes.Object_142.geometry} material={materials.material_0} />
                          </group>
                        </group>
                        <group name="arm_R_103" position={[0.281, -0.063, -0.313]}>
                          <group name="arm_R2_101">
                            <group name="arm_R3_98" position={[0, 0, -0.375]}>
                              <group name="arm_R4_96" position={[0, 0, -0.563]}>
                                <group name="arm_blade_R_93" position={[0, 0, -0.656]}>
                                  <group name="cube_91" position={[0, 0, -0.25]} rotation={[0, 0, -Math.PI / 4]}>
                                    <mesh name="Object_149" geometry={nodes.Object_149.geometry} material={materials.material_0} />
                                  </group>
                                  <group name="cube_92" position={[-0.281, 0.063, 1.125]}>
                                    <mesh name="Object_151" geometry={nodes.Object_151.geometry} material={materials.material_0} />
                                  </group>
                                </group>
                                <group name="cube_94" position={[0, 0, -0.031]}>
                                  <mesh name="Object_153" geometry={nodes.Object_153.geometry} material={materials.material_0} />
                                </group>
                                <group name="cube_95" position={[0, 0, -0.375]} rotation={[0, 0, Math.PI / 4]}>
                                  <mesh name="Object_155" geometry={nodes.Object_155.geometry} material={materials.material_0} />
                                </group>
                              </group>
                              <group name="cube_97" position={[-0.281, 0.063, 0.594]}>
                                <mesh name="Object_157" geometry={nodes.Object_157.geometry} material={materials.material_0} />
                              </group>
                            </group>
                            <group name="cube_99" position={[-0.281, 0.063, 0.063]}>
                              <mesh name="Object_159" geometry={nodes.Object_159.geometry} material={materials.material_0} />
                            </group>
                            <group name="cube_100" position={[0, 0, -0.375]} rotation={[-Math.PI / 4, 0, 0]}>
                              <mesh name="Object_161" geometry={nodes.Object_161.geometry} material={materials.material_0} />
                            </group>
                          </group>
                          <group name="cube_102" rotation={[0, Math.PI / 4, 0]}>
                            <mesh name="Object_163" geometry={nodes.Object_163.geometry} material={materials.material_0} />
                          </group>
                        </group>
                        <group name="arm_L_116" position={[-0.281, -0.063, -0.313]}>
                          <group name="arm_L2_114">
                            <group name="arm_L3_111" position={[0, 0, -0.375]}>
                              <group name="arm_L4_109" position={[0, 0, -0.563]}>
                                <group name="arm_blade_L_106" position={[0, 0, -0.656]}>
                                  <group name="cube_104" position={[0, 0, -0.25]} rotation={[0, 0, Math.PI / 4]}>
                                    <mesh name="Object_170" geometry={nodes.Object_170.geometry} material={materials.material_0} />
                                  </group>
                                  <group name="cube_105" position={[-0.281, 0.063, 1.125]}>
                                    <mesh name="Object_172" geometry={nodes.Object_172.geometry} material={materials.material_0} />
                                  </group>
                                </group>
                                <group name="cube_107" position={[0, 0, -0.375]} rotation={[0, 0, -Math.PI / 4]}>
                                  <mesh name="Object_174" geometry={nodes.Object_174.geometry} material={materials.material_0} />
                                </group>
                                <group name="cube_108" position={[0, 0, -0.031]}>
                                  <mesh name="Object_176" geometry={nodes.Object_176.geometry} material={materials.material_0} />
                                </group>
                              </group>
                              <group name="cube_110" position={[-0.281, 0.063, 0.594]}>
                                <mesh name="Object_178" geometry={nodes.Object_178.geometry} material={materials.material_0} />
                              </group>
                            </group>
                            <group name="cube_112" position={[0, 0, -0.375]} rotation={[-Math.PI / 4, 0, 0]}>
                              <mesh name="Object_180" geometry={nodes.Object_180.geometry} material={materials.material_0} />
                            </group>
                            <group name="cube_113" position={[-0.281, 0.063, 0.063]}>
                              <mesh name="Object_182" geometry={nodes.Object_182.geometry} material={materials.material_0} />
                            </group>
                          </group>
                          <group name="cube_115" rotation={[0, -Math.PI / 4, 0]}>
                            <mesh name="Object_184" geometry={nodes.Object_184.geometry} material={materials.material_0} />
                          </group>
                        </group>
                        <group name="eyes_R_40" position={[0, 0.078, -0.516]} rotation={[0, Math.PI / 4, 0]}>
                          <group name="bone2_35" position={[-0.188, 0.109, -0.047]}>
                            <group name="cube_34" position={[0, -0.109, 0.047]}>
                              <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.material_0} />
                            </group>
                          </group>
                          <group name="bone5_37" position={[-0.219, 0.016, -0.047]}>
                            <group name="cube_36" position={[0, -0.094, 0.047]}>
                              <mesh name="Object_65" geometry={nodes.Object_65.geometry} material={materials.material_0} />
                            </group>
                          </group>
                          <group name="bone8_39" position={[-0.078, 0.063, -0.047]}>
                            <group name="cube_38" position={[0, -0.094, 0.047]}>
                              <mesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials.material_0} />
                            </group>
                          </group>
                        </group>
                        <group name="eyes_L_47" position={[0, 0.078, -0.516]} rotation={[0, -Math.PI / 4, 0]}>
                          <group name="bone_42" position={[0.188, 0.109, -0.047]}>
                            <group name="cube_41" position={[0, -0.109, 0.047]}>
                              <mesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials.material_0} />
                            </group>
                          </group>
                          <group name="bone9_44" position={[0.078, 0.063, -0.047]}>
                            <group name="cube_43" position={[0, -0.094, 0.047]}>
                              <mesh name="Object_75" geometry={nodes.Object_75.geometry} material={materials.material_0} />
                            </group>
                          </group>
                          <group name="bone7_46" position={[0.219, 0.016, -0.047]}>
                            <group name="cube_45" position={[0, -0.094, 0.047]}>
                              <mesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials.material_0} />
                            </group>
                          </group>
                        </group>
                        <group name="Head_blade_49" position={[0, 0.188, -0.5]}>
                          <group name="cube_48" rotation={[-0.463, 0, 0]}>
                            <mesh name="Object_81" geometry={nodes.Object_81.geometry} material={materials.material_0} />
                          </group>
                        </group>
                        <group name="cube_117" position={[0, -0.063, -0.313]} rotation={[0, Math.PI / 4, 0]}>
                          <mesh name="Object_186" geometry={nodes.Object_186.geometry} material={materials.material_0} />
                        </group>
                        <group name="cube_118" position={[0, -0.438, -0.063]}>
                          <mesh name="Object_188" geometry={nodes.Object_188.geometry} material={materials.material_0} />
                        </group>
                        <group name="cube_119" position={[0, 0, 0.25]} rotation={[0, 0, -Math.PI / 4]}>
                          <mesh name="Object_190" geometry={nodes.Object_190.geometry} material={materials.material_0} />
                        </group>
                        <group name="cube_120" position={[0, -0.188, -0.313]} rotation={[0.873, 0, 0]}>
                          <mesh name="Object_192" geometry={nodes.Object_192.geometry} material={materials.material_0} />
                        </group>
                      </group>
                    </group>
                    <group name="limbs_261">
                      <group name="legs_L_191" position={[-0.266, 0.031, 0]}>
                        <group name="leg_L_F_139" position={[0, 0.031, -0.063]}>
                          <group name="leg_L_F2_135" position={[-0.563, 0, 0]}>
                            <group name="leg_L_F3_132" position={[-1.156, 0, 0]}>
                              <group name="leg_L_F4_125" position={[-1.438, 0, 0]}>
                                <group name="cube_123" position={[2.406, -0.109, 0.313]}>
                                  <mesh name="Object_200" geometry={nodes.Object_200.geometry} material={materials.material_0} />
                                </group>
                                <group name="cube_124" position={[4.266, 0, 0]} rotation={[-Math.PI / 4, 0, 0]}>
                                  <mesh name="Object_202" geometry={nodes.Object_202.geometry} material={materials.material_0} />
                                </group>
                              </group>
                              <group name="cube_126" position={[2.828, 0, 0]} rotation={[-Math.PI / 4, 0, 0]}>
                                <mesh name="Object_204" geometry={nodes.Object_204.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_127" rotation={[0, Math.PI / 4, 0]}>
                                <mesh name="Object_206" geometry={nodes.Object_206.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_128" position={[0, 0, -0.375]} rotation={[0, 0, -0.96]}>
                                <mesh name="Object_208" geometry={nodes.Object_208.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_129" rotation={[0, 0, -1.134]}>
                                <mesh name="Object_210" geometry={nodes.Object_210.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_130" position={[2.281, 0, 0.063]}>
                                <mesh name="Object_212" geometry={nodes.Object_212.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_131" position={[-1.438, 0, 0]} rotation={[0, 0, Math.PI / 4]}>
                                <mesh name="Object_214" geometry={nodes.Object_214.geometry} material={materials.material_0} />
                              </group>
                            </group>
                            <group name="cube_133" position={[1.125, 0, 0.063]}>
                              <mesh name="Object_216" geometry={nodes.Object_216.geometry} material={materials.material_0} />
                            </group>
                            <group name="cube_134" position={[-0.109, 0.031, 0]} rotation={[-Math.PI / 4, 0, 0]}>
                              <mesh name="Object_218" geometry={nodes.Object_218.geometry} material={materials.material_0} />
                            </group>
                          </group>
                          <group name="cube_136" position={[0.125, -0.063, 0.313]}>
                            <mesh name="Object_220" geometry={nodes.Object_220.geometry} material={materials.material_0} />
                          </group>
                          <group name="cube_137" position={[-0.063, 0, 0]} rotation={[0, Math.PI / 4, 0]}>
                            <mesh name="Object_222" geometry={nodes.Object_222.geometry} material={materials.material_0} />
                          </group>
                          <group name="cube_138" position={[-0.563, 0.031, 0]} rotation={[0, 0, Math.PI / 4]}>
                            <mesh name="Object_224" geometry={nodes.Object_224.geometry} material={materials.material_0} />
                          </group>
                        </group>
                        <group name="leg_L_B_156" position={[0, 0.031, 0.063]}>
                          <group name="leg_L_B2_152" position={[-0.563, 0, 0]}>
                            <group name="leg_L_B3_149" position={[-1.156, 0, 0]}>
                              <group name="leg_L_B4_142" position={[-1.438, 0, 0]}>
                                <group name="cube_140" position={[2.406, -0.109, 0.188]}>
                                  <mesh name="Object_230" geometry={nodes.Object_230.geometry} material={materials.material_0} />
                                </group>
                                <group name="cube_141" position={[4.266, 0, 0]} rotation={[-Math.PI / 4, 0, 0]}>
                                  <mesh name="Object_232" geometry={nodes.Object_232.geometry} material={materials.material_0} />
                                </group>
                              </group>
                              <group name="cube_143" position={[2.828, 0, 0]} rotation={[-Math.PI / 4, 0, 0]}>
                                <mesh name="Object_234" geometry={nodes.Object_234.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_144" rotation={[0, -Math.PI / 4, 0]}>
                                <mesh name="Object_236" geometry={nodes.Object_236.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_145" position={[0, 0, -0.375]} rotation={[0, 0, -0.96]}>
                                <mesh name="Object_238" geometry={nodes.Object_238.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_146" position={[0, 0, -0.125]} rotation={[0, 0, -1.134]}>
                                <mesh name="Object_240" geometry={nodes.Object_240.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_147" position={[2.281, 0, -0.063]}>
                                <mesh name="Object_242" geometry={nodes.Object_242.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_148" position={[-1.438, 0, 0]} rotation={[0, 0, Math.PI / 4]}>
                                <mesh name="Object_244" geometry={nodes.Object_244.geometry} material={materials.material_0} />
                              </group>
                            </group>
                            <group name="cube_150" position={[1.125, 0, -0.063]}>
                              <mesh name="Object_246" geometry={nodes.Object_246.geometry} material={materials.material_0} />
                            </group>
                            <group name="cube_151" position={[-0.109, 0.031, 0]} rotation={[-Math.PI / 4, 0, 0]}>
                              <mesh name="Object_248" geometry={nodes.Object_248.geometry} material={materials.material_0} />
                            </group>
                          </group>
                          <group name="cube_153" position={[0.125, -0.063, 0.188]}>
                            <mesh name="Object_250" geometry={nodes.Object_250.geometry} material={materials.material_0} />
                          </group>
                          <group name="cube_154" position={[-0.063, 0, 0]} rotation={[0, -Math.PI / 4, 0]}>
                            <mesh name="Object_252" geometry={nodes.Object_252.geometry} material={materials.material_0} />
                          </group>
                          <group name="cube_155" position={[-0.563, 0.031, 0]} rotation={[0, 0, Math.PI / 4]}>
                            <mesh name="Object_254" geometry={nodes.Object_254.geometry} material={materials.material_0} />
                          </group>
                        </group>
                        <group name="leg_L_B_B_173" position={[0, -0.031, 0.188]}>
                          <group name="leg_L_B_B2_169" position={[-0.438, 0, 0]}>
                            <group name="leg_L_B_B3_166" position={[-1.156, 0, 0]}>
                              <group name="leg_L_B_B4_159" position={[-1.438, 0, 0]}>
                                <group name="cube_157" position={[2.281, -0.047, 0.063]}>
                                  <mesh name="Object_260" geometry={nodes.Object_260.geometry} material={materials.material_0} />
                                </group>
                                <group name="cube_158" position={[4.016, 0, 0]} rotation={[-Math.PI / 4, 0, 0]}>
                                  <mesh name="Object_262" geometry={nodes.Object_262.geometry} material={materials.material_0} />
                                </group>
                              </group>
                              <group name="cube_160" position={[2.578, 0, 0]} rotation={[-Math.PI / 4, 0, 0]}>
                                <mesh name="Object_264" geometry={nodes.Object_264.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_161" rotation={[0, -Math.PI / 4, 0]}>
                                <mesh name="Object_266" geometry={nodes.Object_266.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_162" position={[0, 0.016, -0.375]} rotation={[0, 0, -1.134]}>
                                <mesh name="Object_268" geometry={nodes.Object_268.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_163" position={[0, 0.016, -0.375]} rotation={[0, 0, -1.309]}>
                                <mesh name="Object_270" geometry={nodes.Object_270.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_164" position={[2.156, 0.063, -0.188]}>
                                <mesh name="Object_272" geometry={nodes.Object_272.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_165" position={[-1.438, 0, 0]} rotation={[0, 0, Math.PI / 4]}>
                                <mesh name="Object_274" geometry={nodes.Object_274.geometry} material={materials.material_0} />
                              </group>
                            </group>
                            <group name="cube_167" position={[1, 0.063, -0.188]}>
                              <mesh name="Object_276" geometry={nodes.Object_276.geometry} material={materials.material_0} />
                            </group>
                            <group name="cube_168" position={[-0.109, 0.031, 0]} rotation={[Math.PI / 4, 0, 0]}>
                              <mesh name="Object_278" geometry={nodes.Object_278.geometry} material={materials.material_0} />
                            </group>
                          </group>
                          <group name="cube_170" position={[0.125, 0, 0.063]}>
                            <mesh name="Object_280" geometry={nodes.Object_280.geometry} material={materials.material_0} />
                          </group>
                          <group name="cube_171" position={[-0.063, 0, 0]} rotation={[0, Math.PI / 4, 0]}>
                            <mesh name="Object_282" geometry={nodes.Object_282.geometry} material={materials.material_0} />
                          </group>
                          <group name="cube_172" position={[-0.438, 0.031, 0]} rotation={[0, 0, Math.PI / 4]}>
                            <mesh name="Object_284" geometry={nodes.Object_284.geometry} material={materials.material_0} />
                          </group>
                        </group>
                        <group name="leg_L_F_F_190" position={[0, -0.031, -0.188]}>
                          <group name="leg_L_F_F2_186" position={[-0.438, 0, 0]}>
                            <group name="leg_L_F_F3_183" position={[-1.156, 0, 0]}>
                              <group name="leg_L_F_F4_176" position={[-1.438, 0, 0]}>
                                <group name="cube_174" position={[2.281, -0.016, 0.438]}>
                                  <mesh name="Object_290" geometry={nodes.Object_290.geometry} material={materials.material_0} />
                                </group>
                                <group name="cube_175" position={[4.016, 0, 0]} rotation={[-Math.PI / 4, 0, 0]}>
                                  <mesh name="Object_292" geometry={nodes.Object_292.geometry} material={materials.material_0} />
                                </group>
                              </group>
                              <group name="cube_177" position={[2.578, 0, 0]} rotation={[-Math.PI / 4, 0, 0]}>
                                <mesh name="Object_294" geometry={nodes.Object_294.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_178" rotation={[0, Math.PI / 4, 0]}>
                                <mesh name="Object_296" geometry={nodes.Object_296.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_179" position={[0, 0.016, 0]} rotation={[0, 0, -1.134]}>
                                <mesh name="Object_298" geometry={nodes.Object_298.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_180" position={[0, 0.016, 0]} rotation={[0, 0, -1.309]}>
                                <mesh name="Object_300" geometry={nodes.Object_300.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_181" position={[2.156, 0.063, 0.188]}>
                                <mesh name="Object_302" geometry={nodes.Object_302.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_182" position={[-1.438, 0, 0]} rotation={[0, 0, Math.PI / 4]}>
                                <mesh name="Object_304" geometry={nodes.Object_304.geometry} material={materials.material_0} />
                              </group>
                            </group>
                            <group name="cube_184" position={[1, 0.063, 0.188]}>
                              <mesh name="Object_306" geometry={nodes.Object_306.geometry} material={materials.material_0} />
                            </group>
                            <group name="cube_185" position={[-0.109, 0.031, 0]} rotation={[Math.PI / 4, 0, 0]}>
                              <mesh name="Object_308" geometry={nodes.Object_308.geometry} material={materials.material_0} />
                            </group>
                          </group>
                          <group name="cube_187" position={[0.125, 0, 0.438]}>
                            <mesh name="Object_310" geometry={nodes.Object_310.geometry} material={materials.material_0} />
                          </group>
                          <group name="cube_188" position={[-0.063, 0, 0]} rotation={[0, -Math.PI / 4, 0]}>
                            <mesh name="Object_312" geometry={nodes.Object_312.geometry} material={materials.material_0} />
                          </group>
                          <group name="cube_189" position={[-0.438, 0.031, 0]} rotation={[0, 0, Math.PI / 4]}>
                            <mesh name="Object_314" geometry={nodes.Object_314.geometry} material={materials.material_0} />
                          </group>
                        </group>
                      </group>
                      <group name="legs_R_260" position={[0.266, 0.031, 0]}>
                        <group name="leg_R_F_208" position={[0, 0.031, -0.063]}>
                          <group name="leg_R_F2_204" position={[0.563, 0, 0]}>
                            <group name="leg_R_F3_201" position={[1.156, 0, 0]}>
                              <group name="leg_R_F4_194" position={[1.438, 0, 0]}>
                                <group name="cube_192" position={[-2.406, -0.109, 0.313]}>
                                  <mesh name="Object_321" geometry={nodes.Object_321.geometry} material={materials.material_0} />
                                </group>
                                <group name="cube_193" position={[-0.547, 0, 0]} rotation={[-Math.PI / 4, 0, 0]}>
                                  <mesh name="Object_323" geometry={nodes.Object_323.geometry} material={materials.material_0} />
                                </group>
                              </group>
                              <group name="cube_195" position={[0.891, 0, 0]} rotation={[-Math.PI / 4, 0, 0]}>
                                <mesh name="Object_325" geometry={nodes.Object_325.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_196" rotation={[0, -Math.PI / 4, 0]}>
                                <mesh name="Object_327" geometry={nodes.Object_327.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_197" position={[0, 0, -0.375]} rotation={[0, 0, 0.96]}>
                                <mesh name="Object_329" geometry={nodes.Object_329.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_198" rotation={[0, 0, 1.134]}>
                                <mesh name="Object_331" geometry={nodes.Object_331.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_199" position={[-1.688, 0, 0.063]}>
                                <mesh name="Object_333" geometry={nodes.Object_333.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_200" position={[1.438, 0, 0]} rotation={[0, 0, -Math.PI / 4]}>
                                <mesh name="Object_335" geometry={nodes.Object_335.geometry} material={materials.material_0} />
                              </group>
                            </group>
                            <group name="cube_202" position={[-0.25, 0, 0.063]}>
                              <mesh name="Object_337" geometry={nodes.Object_337.geometry} material={materials.material_0} />
                            </group>
                            <group name="cube_203" position={[0.859, 0.031, 0]} rotation={[-Math.PI / 4, 0, 0]}>
                              <mesh name="Object_339" geometry={nodes.Object_339.geometry} material={materials.material_0} />
                            </group>
                          </group>
                          <group name="cube_205" position={[-0.125, -0.063, 0.313]}>
                            <mesh name="Object_341" geometry={nodes.Object_341.geometry} material={materials.material_0} />
                          </group>
                          <group name="cube_206" position={[0.063, 0, 0]} rotation={[0, -Math.PI / 4, 0]}>
                            <mesh name="Object_343" geometry={nodes.Object_343.geometry} material={materials.material_0} />
                          </group>
                          <group name="cube_207" position={[0.563, 0.031, 0]} rotation={[0, 0, -Math.PI / 4]}>
                            <mesh name="Object_345" geometry={nodes.Object_345.geometry} material={materials.material_0} />
                          </group>
                        </group>
                        <group name="leg_R_B_225" position={[0, 0.031, 0.063]}>
                          <group name="leg_R_B2_221" position={[0.563, 0, 0]}>
                            <group name="leg_R_B3_218" position={[1.156, 0, 0]}>
                              <group name="leg_R_B4_211" position={[1.438, 0, 0]}>
                                <group name="cube_209" position={[-0.547, 0, 0]} rotation={[-Math.PI / 4, 0, 0]}>
                                  <mesh name="Object_351" geometry={nodes.Object_351.geometry} material={materials.material_0} />
                                </group>
                                <group name="cube_210" position={[-2.406, -0.109, 0.313]}>
                                  <mesh name="Object_353" geometry={nodes.Object_353.geometry} material={materials.material_0} />
                                </group>
                              </group>
                              <group name="cube_212" position={[0, 0, -0.375]} rotation={[0, 0, 0.96]}>
                                <mesh name="Object_355" geometry={nodes.Object_355.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_213" rotation={[0, 0, 1.134]}>
                                <mesh name="Object_357" geometry={nodes.Object_357.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_214" rotation={[0, Math.PI / 4, 0]}>
                                <mesh name="Object_359" geometry={nodes.Object_359.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_215" position={[-1.688, 0, 0.063]}>
                                <mesh name="Object_361" geometry={nodes.Object_361.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_216" position={[0.891, 0, 0]} rotation={[-Math.PI / 4, 0, 0]}>
                                <mesh name="Object_363" geometry={nodes.Object_363.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_217" position={[1.438, 0, 0]} rotation={[0, 0, -Math.PI / 4]}>
                                <mesh name="Object_365" geometry={nodes.Object_365.geometry} material={materials.material_0} />
                              </group>
                            </group>
                            <group name="cube_219" position={[0.859, 0.031, 0]} rotation={[-Math.PI / 4, 0, 0]}>
                              <mesh name="Object_367" geometry={nodes.Object_367.geometry} material={materials.material_0} />
                            </group>
                            <group name="cube_220" position={[-0.25, 0, 0.063]}>
                              <mesh name="Object_369" geometry={nodes.Object_369.geometry} material={materials.material_0} />
                            </group>
                          </group>
                          <group name="cube_222" position={[0.063, 0, 0]} rotation={[0, Math.PI / 4, 0]}>
                            <mesh name="Object_371" geometry={nodes.Object_371.geometry} material={materials.material_0} />
                          </group>
                          <group name="cube_223" position={[-0.125, -0.063, 0.313]}>
                            <mesh name="Object_373" geometry={nodes.Object_373.geometry} material={materials.material_0} />
                          </group>
                          <group name="cube_224" position={[0.563, 0.031, 0]} rotation={[0, 0, -Math.PI / 4]}>
                            <mesh name="Object_375" geometry={nodes.Object_375.geometry} material={materials.material_0} />
                          </group>
                        </group>
                        <group name="leg_R_F_F_242" position={[0, -0.031, -0.188]}>
                          <group name="leg_R_F_F2_238" position={[0.438, 0, 0]}>
                            <group name="leg_R_F_F3_235" position={[1.156, 0, 0]}>
                              <group name="leg_R_F_F4_228" position={[1.438, 0, 0]}>
                                <group name="cube_226" position={[-2.281, -0.047, 0.438]}>
                                  <mesh name="Object_381" geometry={nodes.Object_381.geometry} material={materials.material_0} />
                                </group>
                                <group name="cube_227" position={[-0.547, 0, 0]} rotation={[-Math.PI / 4, 0, 0]}>
                                  <mesh name="Object_383" geometry={nodes.Object_383.geometry} material={materials.material_0} />
                                </group>
                              </group>
                              <group name="cube_229" position={[0.891, 0, 0]} rotation={[-Math.PI / 4, 0, 0]}>
                                <mesh name="Object_385" geometry={nodes.Object_385.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_230" rotation={[0, -Math.PI / 4, 0]}>
                                <mesh name="Object_387" geometry={nodes.Object_387.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_231" position={[0, 0.016, 0]} rotation={[0, 0, 1.134]}>
                                <mesh name="Object_389" geometry={nodes.Object_389.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_232" position={[0, 0.016, 0]} rotation={[0, 0, 1.309]}>
                                <mesh name="Object_391" geometry={nodes.Object_391.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_233" position={[-1.563, 0.063, 0.188]}>
                                <mesh name="Object_393" geometry={nodes.Object_393.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_234" position={[1.438, 0, 0]} rotation={[0, 0, -Math.PI / 4]}>
                                <mesh name="Object_395" geometry={nodes.Object_395.geometry} material={materials.material_0} />
                              </group>
                            </group>
                            <group name="cube_236" position={[-0.125, 0.063, 0.188]}>
                              <mesh name="Object_397" geometry={nodes.Object_397.geometry} material={materials.material_0} />
                            </group>
                            <group name="cube_237" position={[0.859, 0.031, 0]} rotation={[Math.PI / 4, 0, 0]}>
                              <mesh name="Object_399" geometry={nodes.Object_399.geometry} material={materials.material_0} />
                            </group>
                          </group>
                          <group name="cube_239" position={[-0.125, 0, 0.438]}>
                            <mesh name="Object_401" geometry={nodes.Object_401.geometry} material={materials.material_0} />
                          </group>
                          <group name="cube_240" position={[0.063, 0, 0]} rotation={[0, Math.PI / 4, 0]}>
                            <mesh name="Object_403" geometry={nodes.Object_403.geometry} material={materials.material_0} />
                          </group>
                          <group name="cube_241" position={[0.438, 0.031, 0]} rotation={[0, 0, -Math.PI / 4]}>
                            <mesh name="Object_405" geometry={nodes.Object_405.geometry} material={materials.material_0} />
                          </group>
                        </group>
                        <group name="leg_R_B_B_259" position={[0, -0.031, 0.188]}>
                          <group name="leg_R_B_B2_255" position={[0.438, 0, 0]}>
                            <group name="leg_R_B_B3_252" position={[1.156, 0, 0]}>
                              <group name="leg_R_B_B4_245" position={[1.438, 0, 0]}>
                                <group name="cube_243" position={[-0.547, 0, 0]} rotation={[-Math.PI / 4, 0, 0]}>
                                  <mesh name="Object_411" geometry={nodes.Object_411.geometry} material={materials.material_0} />
                                </group>
                                <group name="cube_244" position={[-2.281, -0.047, 0.438]}>
                                  <mesh name="Object_413" geometry={nodes.Object_413.geometry} material={materials.material_0} />
                                </group>
                              </group>
                              <group name="cube_246" position={[0, 0.016, 0]} rotation={[0, 0, 1.134]}>
                                <mesh name="Object_415" geometry={nodes.Object_415.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_247" position={[0, 0.016, 0]} rotation={[0, 0, 1.309]}>
                                <mesh name="Object_417" geometry={nodes.Object_417.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_248" rotation={[0, Math.PI / 4, 0]}>
                                <mesh name="Object_419" geometry={nodes.Object_419.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_249" position={[0.891, 0, 0]} rotation={[-Math.PI / 4, 0, 0]}>
                                <mesh name="Object_421" geometry={nodes.Object_421.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_250" position={[-1.563, 0.063, 0.188]}>
                                <mesh name="Object_423" geometry={nodes.Object_423.geometry} material={materials.material_0} />
                              </group>
                              <group name="cube_251" position={[1.438, 0, 0]} rotation={[0, 0, -Math.PI / 4]}>
                                <mesh name="Object_425" geometry={nodes.Object_425.geometry} material={materials.material_0} />
                              </group>
                            </group>
                            <group name="cube_253" position={[-0.125, 0.063, 0.188]}>
                              <mesh name="Object_427" geometry={nodes.Object_427.geometry} material={materials.material_0} />
                            </group>
                            <group name="cube_254" position={[0.859, 0.031, 0]} rotation={[Math.PI / 4, 0, 0]}>
                              <mesh name="Object_429" geometry={nodes.Object_429.geometry} material={materials.material_0} />
                            </group>
                          </group>
                          <group name="cube_256" position={[0.063, 0, 0]} rotation={[0, -Math.PI / 4, 0]}>
                            <mesh name="Object_431" geometry={nodes.Object_431.geometry} material={materials.material_0} />
                          </group>
                          <group name="cube_257" position={[-0.125, 0, 0.438]}>
                            <mesh name="Object_433" geometry={nodes.Object_433.geometry} material={materials.material_0} />
                          </group>
                          <group name="cube_258" position={[0.438, 0.031, 0]} rotation={[0, 0, -Math.PI / 4]}>
                            <mesh name="Object_435" geometry={nodes.Object_435.geometry} material={materials.material_0} />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/monsters/void-spider/source/voided_spider.glb')
