// Code Review Royale content. `answer` is 'approve' or 'request'.
// `catastrophic` PRs blow up production if approved (extra penalty + effect).

export const PULL_REQUESTS = [
  {
    title: 'Fix typo in banana inventory page',
    author: 'dana',
    stats: '+1 −1',
    diff: [['-', '<h1>Banana Inventroy</h1>'], ['+', '<h1>Banana Inventory</h1>']],
    answer: 'approve',
  },
  {
    title: 'Refactor authentication',
    author: 'ceo-nephew',
    stats: '+1,247 −3',
    description: 'small cleanup',
    diff: [[' ', 'function login(user, password) {'], ['+', "  if (user.name === 'admin') return true"], ['+', '  console.log("password", password)'], [' ', '  return checkPassword(user, password)']],
    answer: 'request',
  },
  {
    title: 'Small cleanup',
    author: 'kevin',
    stats: '+1 −84,211',
    description: 'removed unused stuff',
    diff: [['-', 'production_database/'], ['-', '  (84,210 files)'], ['+', 'README.md']],
    answer: 'request',
    catastrophic: true,
  },
  {
    title: 'Add unit tests for banana pricing',
    author: 'priya',
    stats: '+120 −0',
    diff: [['+', "test('bananas are never $0.00', () => {"], ['+', '  expect(price(banana)).toBeGreaterThan(0)'], ['+', '})']],
    answer: 'approve',
  },
  {
    title: 'Fix race condition',
    author: 'dave',
    stats: '+1 −0',
    diff: [[' ', 'await saveOrder(order)'], ['+', 'await sleep(5000) // fixes it (usually)'], [' ', 'await chargeCard(order)']],
    answer: 'request',
  },
  {
    title: 'Hotfix: unblock release',
    author: 'greg',
    stats: '+3 −0',
    description: 'tests were being negative',
    diff: [['+', 'describe.skip("checkout", () => {'], ['+', 'describe.skip("payments", () => {'], ['+', 'describe.skip("everything", () => {']],
    answer: 'request',
  },
  {
    title: 'Rename x to bananaCount',
    author: 'dana',
    stats: '+2 −2',
    diff: [['-', 'let x = 0'], ['+', 'let bananaCount = 0'], ['-', 'x++'], ['+', 'bananaCount++']],
    answer: 'approve',
  },
  {
    title: 'Add Stripe integration',
    author: 'intern',
    stats: '+1 −0',
    diff: [['+', 'const STRIPE_KEY = "sk_live_51HbAnAnA_DoNotShare_lol"']],
    answer: 'request',
    catastrophic: true,
  },
  {
    title: 'Improve error handling',
    author: 'kevin',
    stats: '+3 −12',
    description: 'errors are a mindset',
    diff: [['-', '  throw new PaymentError(e)'], ['+', 'try { pay() }'], ['+', 'catch (e) {}']],
    answer: 'request',
  },
  {
    title: 'Add retries with exponential backoff',
    author: 'priya',
    stats: '+18 −4',
    diff: [['+', 'for (let i = 0; i < 5; i++) {'], ['+', '  try { return await call() }'], ['+', '  catch { await sleep(2 ** i * 100) }'], ['+', '}']],
    answer: 'approve',
  },
  {
    title: 'Bump banana-utils 4.2.1 → 4.2.2',
    author: 'dependabot',
    stats: '+1 −1',
    description: 'CI: ✅ all checks passed',
    diff: [['-', '"banana-utils": "4.2.1"'], ['+', '"banana-utils": "4.2.2"']],
    answer: 'approve',
  },
  {
    title: 'Boost engagement',
    author: 'svp-of-synergy',
    stats: '+3 −0',
    diff: [['+', 'while (true) {'], ['+', '  synergy++'], ['+', '}']],
    answer: 'request',
  },
  {
    title: 'Remove dead code',
    author: 'dana',
    stats: '+0 −412',
    description: 'unused since 2019, tests green',
    diff: [['-', 'function legacyBananaExport_OLD_v2_FINAL() {'], ['-', '  // nobody calls this'], ['-', '}']],
    answer: 'approve',
  },
  {
    title: 'Make all buttons yellow',
    author: 'chief-banana-officer',
    stats: '+1 −1',
    diff: [['-', 'button { color: blue; }'], ['+', 'button { color: #FFE135; }']],
    answer: 'approve',
  },
  {
    title: 'Migration: tidy up users table',
    author: 'kevin',
    stats: '+1 −0',
    description: 'tidy',
    diff: [['+', 'DROP TABLE users;']],
    answer: 'request',
    catastrophic: true,
  },
  // FAANG / public-postmortem deck
  {
    title: 'Generate one-year certs',
    author: 'macrohard-intern',
    stats: '+1 −1',
    description: 'merged Feb 29',
    diff: [['-', 'expiry = addDays(now, 365)'], ['+', 'expiry = new Date(now.year + 1, now.month, now.day)']],
    flavor: 'February 29th, next year. What could go wrong?',
    answer: 'request',
    catastrophic: true,
  },
  {
    title: 'Faster WAF rule',
    author: 'edge-team',
    stats: '+1 −0',
    diff: [['+', 'match: /.*(?:.*=.*)/  # deploy to every edge, globally']],
    flavor: 'Catastrophic backtracking is still backtracking.',
    answer: 'request',
    catastrophic: true,
  },
  {
    title: 'Remove a few billing servers for debugging',
    author: 'brws-oncall',
    stats: '+1 −0',
    description: 'following the playbook',
    diff: [['+', 'playbook remove-capacity --count=1000  # meant 10']],
    flavor: 'A larger set of servers than intended.',
    answer: 'request',
    catastrophic: true,
  },
  {
    title: 'Reuse an old feature flag',
    author: 'trading-desk',
    stats: '+1 −0',
    description: 'flag unused since 2003',
    diff: [['+', 'if (flags.POWER_PEG) { buyEverything() }']],
    flavor: 'Dead code is only mostly dead.',
    answer: 'request',
  },
  {
    title: 'Push config update to all hosts',
    author: 'kevin',
    stats: '+2 −2',
    description: "Friday 4:55 PM, it's just a content file",
    diff: [['-', 'rollout: canary → 1% → 10% → 100%'], ['+', 'rollout: 100%  # everyone, now']],
    flavor: 'Blue screens are a kind of status page.',
    answer: 'request',
    catastrophic: true,
  },
  {
    title: 'Add canary stage before global rollout',
    author: 'priya',
    stats: '+6 −1',
    diff: [['-', 'rollout: 100%'], ['+', 'rollout: [canary, 1%, 10%, 100%]'], ['+', 'halt_on: error_rate > 0.1%']],
    answer: 'approve',
  },
  {
    title: 'Add leap-year tests for cert expiry',
    author: 'dana',
    stats: '+14 −0',
    diff: [['+', "test('cert issued Feb 29 expires on a real date', () => {"], ['+', "  expect(expiry('2024-02-29')).toBeValidDate()"], ['+', '})']],
    answer: 'approve',
  },
  {
    title: 'Rate-limit reply-all on huge distribution lists',
    author: 'macrohard-exchange',
    stats: '+9 −0',
    diff: [['+', 'if (dl.members > 5000) requireModeration(dl)']],
    flavor: 'Never again, BEDLAM-DL3.',
    answer: 'approve',
  },
  {
    title: 'Add TODO',
    author: 'dave',
    stats: '+1 −0',
    diff: [['+', '// TODO: fix this later (2017)']],
    answer: 'request',
  },
]

// File shown in the "Files changed" header, by PR title
const FILES = {
  'Fix typo in banana inventory page': 'src/pages/inventory.html',
  'Refactor authentication': 'src/auth/login.js',
  'Small cleanup': 'production_database/**',
  'Add unit tests for banana pricing': 'test/pricing.test.js',
  'Fix race condition': 'src/orders/checkout.js',
  'Hotfix: unblock release': 'test/checkout.test.js',
  'Rename x to bananaCount': 'src/inventory/count.js',
  'Add Stripe integration': 'src/payments/stripe.js',
  'Improve error handling': 'src/payments/pay.js',
  'Add retries with exponential backoff': 'src/net/retry.js',
  'Bump banana-utils 4.2.1 → 4.2.2': 'package.json',
  'Boost engagement': 'src/growth/engagement.js',
  'Remove dead code': 'src/legacy/export.js',
  'Make all buttons yellow': 'src/styles/buttons.css',
  'Migration: tidy up users table': 'db/migrations/0042_tidy.sql',
  'Generate one-year certs': 'src/certs/Issue.cs',
  'Faster WAF rule': 'edge/waf/rules.yaml',
  'Remove a few billing servers for debugging': 'playbooks/billing-debug.sh',
  'Reuse an old feature flag': 'src/trading/router.cpp',
  'Push config update to all hosts': 'deploy/rollout.yaml',
  'Add canary stage before global rollout': 'deploy/rollout.yaml',
  'Add leap-year tests for cert expiry': 'test/Certs.Tests.cs',
  'Rate-limit reply-all on huge distribution lists': 'src/mail/distributionList.ts',
  'Add TODO': 'src/everything.js',
}
export const fileFor = (pr) => FILES[pr.title] ?? 'src/index.js'

export const APPROVE_LINES = ['LGTM 🍌', 'Approved. You are a 10x reviewer.', 'Merged. Nothing bad happened. Yet.']
export const REQUEST_LINES = ['Changes requested. The author has left the company.', 'Good catch. Kevin has been "re-orged."', 'Blocked. Production thanks you.']
export const WRONG_LINES = ['That was not it.', 'The linter is weeping.', 'Greg saw that.']
