/**
 * SCENE TEMPLATE
 *
 * Use this template to create new scenes with pickup/drop functionality
 * Just copy this file, rename it, and customize the SCENE_ITEMS array
 */

import React, { useRef, useEffect, useCallback } from 'react';
import { Physics } from '@react-three/rapier';
import FirstPersonPlayer from '../components/Player/FirstPersonPlayer';
import PickupController from '../components/Player/PickupController';
import DropHandler from '../components/Gameplay/DropHandler';
import { usePickupDrop } from '../hooks/usePickupDrop';
import { getItemConfig } from '../config/pickupItems';
import { ITEM_COMPONENTS } from '../components/Props/ItemRegistry';
import { createSceneItems } from '../utils/sceneHelpers';
import { useGameSave, buildGameState } from '../hooks/useGameSave';
import { useInventoryStore } from '../storage/inventoryStore';

/**
 * Scene Items - Define all pickup items for this scene
 *
 * Structure:
 * - type: Component type from ItemRegistry (e.g., 'alienBlade', 'oilLampCan', 'torch') - use camelCase
 * - position: [x, y, z] world coordinates
 *
 * Note: IDs are auto-generated by createSceneItems() based on type + position
 * This keeps items stable for save/load while eliminating manual ID typing
 *
 * Available item types (see ItemRegistry.js):
 * - alienBlade (cyan glow, hovering)
 * - oilLampCan (orange light, flickering)
 * - torch (fire particles, orange light) - TODO: create this
 * - healthPotion (green sparkles) - TODO: create this
 * - key (gold glow, jingle) - TODO: create this
 */
const SCENE_ITEMS = createSceneItems([
  // Example items - customize for your scene:
  { type: 'alienBlade', position: [10, 0, 5] },
  { type: 'oilLampCan', position: [8, 0, 3] },
  // Add more items as needed...
]);

export default function YourSceneName({ progress, setProgress, onInventoryFull }) {
  const capsuleHeight = 1.6;
  const spawnPoint = [0, capsuleHeight / 2, 0];
  const playerRef = useRef();

  // Use the reusable pickup/drop hook
  const {
    droppedItems,
    setDroppedItems,
    pickedUpStaticItemIds,
    handlePickup,
  } = usePickupDrop(playerRef);

  // Initialize save system
  const { saveNow, saveDebounced } = useGameSave({
    debounceDelay: 3000,
    logSaves: true,
  });

  // Get inventory items from store
  const inventoryItems = useInventoryStore((state) => state.items);

  // Helper to get current game state
  const getCurrentGameState = useCallback(() => {
    return buildGameState({
      currentScene: 'YourSceneName', // Update this to match your scene name
      playerPosition: playerRef.current?.translation?.()?.toArray?.() || [0, capsuleHeight / 2, 0],
      pickedUpItemIds: pickedUpStaticItemIds,
      droppedItems: droppedItems,
      inventory: inventoryItems,
    });
  }, [pickedUpStaticItemIds, droppedItems, inventoryItems, capsuleHeight]);

  // Save on window close
  useEffect(() => {
    const handleBeforeUnload = () => {
      saveNow(getCurrentGameState());
    };

    window.addEventListener('beforeunload', handleBeforeUnload);
    return () => {
      window.removeEventListener('beforeunload', handleBeforeUnload);
    };
  }, [saveNow, getCurrentGameState]);

  return (
    <Physics gravity={[0, -10.81, 0]}>
      {/* Drop handler - detects X key and handles dropping */}
      <DropHandler
        playerRef={playerRef}
        setDroppedItems={setDroppedItems}
        onDrop={() => {
          // Save immediately after dropping an item
          saveNow(getCurrentGameState());
        }}
      />

      {/* Your scene environment */}
      {/* <YourEnvironmentModel position={[0, -5, 0]} /> */}

      {/* Player */}
      <FirstPersonPlayer
        ref={playerRef}
        progress={progress}
        setProgress={setProgress}
        spawnPoint={spawnPoint}
      />

      {/* Your scene-specific entities (enemies, NPCs, etc.) */}
      {/* <YourEnemy position={[0, 0, 10]} /> */}

      {/* Pickup controller - handles E key detection */}
      <PickupController
        playerRef={playerRef}
        onPickup={(id, itemType, item) => {
          const success = handlePickup(id, itemType, item);
          if (success) {
            // Save immediately after successful pickup
            saveNow(getCurrentGameState());
          } else if (onInventoryFull) {
            onInventoryFull();
          }
          return success;
        }}
      />

      {/* Render all scene items using their registered components */}
      {SCENE_ITEMS.filter(item => !pickedUpStaticItemIds.has(item.id)).map(item => {
        const ItemComponent = ITEM_COMPONENTS[item.type];

        if (!ItemComponent) {
          console.error(`No component found for item type: ${item.type}`);
          return null;
        }

        return (
          <ItemComponent
            key={item.id}
            id={item.id}
            position={item.position}
          />
        );
      })}

      {/* Dynamically dropped items - automatically managed */}
      {droppedItems.map((item) => {
        const ItemComponent = ITEM_COMPONENTS[item.itemType];

        if (!ItemComponent) {
          console.warn(`No component for dropped item type: ${item.itemType}`);
          return null;
        }

        return (
          <ItemComponent
            key={`dropped_${item.id}_${item.timestamp}`}
            id={item.id}
            position={item.position}
          />
        );
      })}

    </Physics>
  );
}
