/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 /Users/luis/GithubProjects/CaveGame/my-three-app/public/assets/models/player/AdventurerArms.glb --output src/components/Player/AdventurerArmsModel.tsx --types --bones 
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'Death' | 'Gun_Shoot' | 'HitRecieve' | 'HitRecieve_2' | 'Idle' | 'Idle_Gun' | 'Idle_Gun_Pointing' | 'Idle_Gun_Shoot' | 'Idle_Neutral' | 'Idle_Sword' | 'Interact' | 'Kick_Left' | 'Kick_Right' | 'Punch_Left' | 'Punch_Right' | 'Roll' | 'Run' | 'Run_Back' | 'Run_Left' | 'Run_Right' | 'Run_Shoot' | 'Sword_Slash' | 'Walk' | 'Wave'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Cube063: THREE.SkinnedMesh
    Root: THREE.Bone
    Body: THREE.Bone
    Hips: THREE.Bone
    Abdomen: THREE.Bone
    Torso: THREE.Bone
    Chest: THREE.Bone
    Neck: THREE.Bone
    Head: THREE.Bone
    ShoulderL: THREE.Bone
    UpperArmL: THREE.Bone
    LowerArmL: THREE.Bone
    WristL: THREE.Bone
    Index1L: THREE.Bone
    Index2L: THREE.Bone
    Index3L: THREE.Bone
    Index4L: THREE.Bone
    Middle1L: THREE.Bone
    Middle2L: THREE.Bone
    Middle3L: THREE.Bone
    Middle4L: THREE.Bone
    Ring1L: THREE.Bone
    Ring2L: THREE.Bone
    Ring3L: THREE.Bone
    Ring4L: THREE.Bone
    Pinky1L: THREE.Bone
    Pinky2L: THREE.Bone
    Pinky3L: THREE.Bone
    Pinky4L: THREE.Bone
    Thumb1L: THREE.Bone
    Thumb2L: THREE.Bone
    Thumb3L: THREE.Bone
    ShoulderR: THREE.Bone
    UpperArmR: THREE.Bone
    LowerArmR: THREE.Bone
    WristR: THREE.Bone
    Index1R: THREE.Bone
    Index2R: THREE.Bone
    Index3R: THREE.Bone
    Index4R: THREE.Bone
    Middle1R: THREE.Bone
    Middle2R: THREE.Bone
    Middle3R: THREE.Bone
    Middle4R: THREE.Bone
    Ring1R: THREE.Bone
    Ring2R: THREE.Bone
    Ring3R: THREE.Bone
    Ring4R: THREE.Bone
    Pinky1R: THREE.Bone
    Pinky2R: THREE.Bone
    Pinky3R: THREE.Bone
    Pinky4R: THREE.Bone
    Thumb1R: THREE.Bone
    Thumb2R: THREE.Bone
    Thumb3R: THREE.Bone
    UpperLegL: THREE.Bone
    LowerLegL: THREE.Bone
    UpperLegR: THREE.Bone
    LowerLegR: THREE.Bone
    FootL: THREE.Bone
    PTL: THREE.Bone
    FootR: THREE.Bone
    PTR: THREE.Bone
  }
  materials: {
    Skin: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type BoneRefs = {
  Root: THREE.Bone | null
  Body: THREE.Bone | null
  Hips: THREE.Bone | null
  Abdomen: THREE.Bone | null
  Torso: THREE.Bone | null
  Chest: THREE.Bone | null
  Neck: THREE.Bone | null
  Head: THREE.Bone | null
  ShoulderL: THREE.Bone | null
  UpperArmL: THREE.Bone | null
  LowerArmL: THREE.Bone | null
  WristL: THREE.Bone | null
  Index1L: THREE.Bone | null
  Index2L: THREE.Bone | null
  Index3L: THREE.Bone | null
  Index4L: THREE.Bone | null
  Middle1L: THREE.Bone | null
  Middle2L: THREE.Bone | null
  Middle3L: THREE.Bone | null
  Middle4L: THREE.Bone | null
  Ring1L: THREE.Bone | null
  Ring2L: THREE.Bone | null
  Ring3L: THREE.Bone | null
  Ring4L: THREE.Bone | null
  Pinky1L: THREE.Bone | null
  Pinky2L: THREE.Bone | null
  Pinky3L: THREE.Bone | null
  Pinky4L: THREE.Bone | null
  Thumb1L: THREE.Bone | null
  Thumb2L: THREE.Bone | null
  Thumb3L: THREE.Bone | null
  ShoulderR: THREE.Bone | null
  UpperArmR: THREE.Bone | null
  LowerArmR: THREE.Bone | null
  WristR: THREE.Bone | null
  Index1R: THREE.Bone | null
  Index2R: THREE.Bone | null
  Index3R: THREE.Bone | null
  Index4R: THREE.Bone | null
  Middle1R: THREE.Bone | null
  Middle2R: THREE.Bone | null
  Middle3R: THREE.Bone | null
  Middle4R: THREE.Bone | null
  Ring1R: THREE.Bone | null
  Ring2R: THREE.Bone | null
  Ring3R: THREE.Bone | null
  Ring4R: THREE.Bone | null
  Pinky1R: THREE.Bone | null
  Pinky2R: THREE.Bone | null
  Pinky3R: THREE.Bone | null
  Pinky4R: THREE.Bone | null
  Thumb1R: THREE.Bone | null
  Thumb2R: THREE.Bone | null
  Thumb3R: THREE.Bone | null
  UpperLegL: THREE.Bone | null
  LowerLegL: THREE.Bone | null
  UpperLegR: THREE.Bone | null
  LowerLegR: THREE.Bone | null
  FootL: THREE.Bone | null
  PTL: THREE.Bone | null
  FootR: THREE.Bone | null
  PTR: THREE.Bone | null
  actions: any
  updateMatrixWorld: () => void
}

export const Model = React.forwardRef<BoneRefs, React.ComponentProps<'group'>>((props, ref) => {
  const group = React.useRef<THREE.Group>(null!)
  const { scene, animations } = useGLTF('/assets/models/player/AdventurerArms.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)

  // Create refs for each bone
  const boneRefs = {
    Root: React.useRef<THREE.Bone>(null),
    Body: React.useRef<THREE.Bone>(null),
    Hips: React.useRef<THREE.Bone>(null),
    Abdomen: React.useRef<THREE.Bone>(null),
    Torso: React.useRef<THREE.Bone>(null),
    Chest: React.useRef<THREE.Bone>(null),
    Neck: React.useRef<THREE.Bone>(null),
    Head: React.useRef<THREE.Bone>(null),
    ShoulderL: React.useRef<THREE.Bone>(null),
    UpperArmL: React.useRef<THREE.Bone>(null),
    LowerArmL: React.useRef<THREE.Bone>(null),
    WristL: React.useRef<THREE.Bone>(null),
    Index1L: React.useRef<THREE.Bone>(null),
    Index2L: React.useRef<THREE.Bone>(null),
    Index3L: React.useRef<THREE.Bone>(null),
    Index4L: React.useRef<THREE.Bone>(null),
    Middle1L: React.useRef<THREE.Bone>(null),
    Middle2L: React.useRef<THREE.Bone>(null),
    Middle3L: React.useRef<THREE.Bone>(null),
    Middle4L: React.useRef<THREE.Bone>(null),
    Ring1L: React.useRef<THREE.Bone>(null),
    Ring2L: React.useRef<THREE.Bone>(null),
    Ring3L: React.useRef<THREE.Bone>(null),
    Ring4L: React.useRef<THREE.Bone>(null),
    Pinky1L: React.useRef<THREE.Bone>(null),
    Pinky2L: React.useRef<THREE.Bone>(null),
    Pinky3L: React.useRef<THREE.Bone>(null),
    Pinky4L: React.useRef<THREE.Bone>(null),
    Thumb1L: React.useRef<THREE.Bone>(null),
    Thumb2L: React.useRef<THREE.Bone>(null),
    Thumb3L: React.useRef<THREE.Bone>(null),
    ShoulderR: React.useRef<THREE.Bone>(null),
    UpperArmR: React.useRef<THREE.Bone>(null),
    LowerArmR: React.useRef<THREE.Bone>(null),
    WristR: React.useRef<THREE.Bone>(null),
    Index1R: React.useRef<THREE.Bone>(null),
    Index2R: React.useRef<THREE.Bone>(null),
    Index3R: React.useRef<THREE.Bone>(null),
    Index4R: React.useRef<THREE.Bone>(null),
    Middle1R: React.useRef<THREE.Bone>(null),
    Middle2R: React.useRef<THREE.Bone>(null),
    Middle3R: React.useRef<THREE.Bone>(null),
    Middle4R: React.useRef<THREE.Bone>(null),
    Ring1R: React.useRef<THREE.Bone>(null),
    Ring2R: React.useRef<THREE.Bone>(null),
    Ring3R: React.useRef<THREE.Bone>(null),
    Ring4R: React.useRef<THREE.Bone>(null),
    Pinky1R: React.useRef<THREE.Bone>(null),
    Pinky2R: React.useRef<THREE.Bone>(null),
    Pinky3R: React.useRef<THREE.Bone>(null),
    Pinky4R: React.useRef<THREE.Bone>(null),
    Thumb1R: React.useRef<THREE.Bone>(null),
    Thumb2R: React.useRef<THREE.Bone>(null),
    Thumb3R: React.useRef<THREE.Bone>(null),
    UpperLegL: React.useRef<THREE.Bone>(null),
    LowerLegL: React.useRef<THREE.Bone>(null),
    UpperLegR: React.useRef<THREE.Bone>(null),
    LowerLegR: React.useRef<THREE.Bone>(null),
    FootL: React.useRef<THREE.Bone>(null),
    PTL: React.useRef<THREE.Bone>(null),
    FootR: React.useRef<THREE.Bone>(null),
    PTR: React.useRef<THREE.Bone>(null),
  }

  // Expose bone refs via useImperativeHandle
  React.useImperativeHandle(
    ref,
    () => ({
      Root: boneRefs.Root.current,
      Body: boneRefs.Body.current,
      Hips: boneRefs.Hips.current,
      Abdomen: boneRefs.Abdomen.current,
      Torso: boneRefs.Torso.current,
      Chest: boneRefs.Chest.current,
      Neck: boneRefs.Neck.current,
      Head: boneRefs.Head.current,
      ShoulderL: boneRefs.ShoulderL.current,
      UpperArmL: boneRefs.UpperArmL.current,
      LowerArmL: boneRefs.LowerArmL.current,
      WristL: boneRefs.WristL.current,
      Index1L: boneRefs.Index1L.current,
      Index2L: boneRefs.Index2L.current,
      Index3L: boneRefs.Index3L.current,
      Index4L: boneRefs.Index4L.current,
      Middle1L: boneRefs.Middle1L.current,
      Middle2L: boneRefs.Middle2L.current,
      Middle3L: boneRefs.Middle3L.current,
      Middle4L: boneRefs.Middle4L.current,
      Ring1L: boneRefs.Ring1L.current,
      Ring2L: boneRefs.Ring2L.current,
      Ring3L: boneRefs.Ring3L.current,
      Ring4L: boneRefs.Ring4L.current,
      Pinky1L: boneRefs.Pinky1L.current,
      Pinky2L: boneRefs.Pinky2L.current,
      Pinky3L: boneRefs.Pinky3L.current,
      Pinky4L: boneRefs.Pinky4L.current,
      Thumb1L: boneRefs.Thumb1L.current,
      Thumb2L: boneRefs.Thumb2L.current,
      Thumb3L: boneRefs.Thumb3L.current,
      ShoulderR: boneRefs.ShoulderR.current,
      UpperArmR: boneRefs.UpperArmR.current,
      LowerArmR: boneRefs.LowerArmR.current,
      WristR: boneRefs.WristR.current,
      Index1R: boneRefs.Index1R.current,
      Index2R: boneRefs.Index2R.current,
      Index3R: boneRefs.Index3R.current,
      Index4R: boneRefs.Index4R.current,
      Middle1R: boneRefs.Middle1R.current,
      Middle2R: boneRefs.Middle2R.current,
      Middle3R: boneRefs.Middle3R.current,
      Middle4R: boneRefs.Middle4R.current,
      Ring1R: boneRefs.Ring1R.current,
      Ring2R: boneRefs.Ring2R.current,
      Ring3R: boneRefs.Ring3R.current,
      Ring4R: boneRefs.Ring4R.current,
      Pinky1R: boneRefs.Pinky1R.current,
      Pinky2R: boneRefs.Pinky2R.current,
      Pinky3R: boneRefs.Pinky3R.current,
      Pinky4R: boneRefs.Pinky4R.current,
      Thumb1R: boneRefs.Thumb1R.current,
      Thumb2R: boneRefs.Thumb2R.current,
      Thumb3R: boneRefs.Thumb3R.current,
      UpperLegL: boneRefs.UpperLegL.current,
      LowerLegL: boneRefs.LowerLegL.current,
      UpperLegR: boneRefs.UpperLegR.current,
      LowerLegR: boneRefs.LowerLegR.current,
      FootL: boneRefs.FootL.current,
      PTL: boneRefs.PTL.current,
      FootR: boneRefs.FootR.current,
      PTR: boneRefs.PTR.current,
      actions,
      updateMatrixWorld: () => {
        if (group.current) {
          group.current.updateMatrixWorld(true)
        }
      },
    }),
    [actions],
  )
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Adventurergltf">
          <group name="CharacterArmature">
            <primitive object={nodes.Root} ref={boneRefs.Root} name="Root" position={[0, 0, 0.072]}>
              <primitive object={nodes.Body} ref={boneRefs.Body} name="Body" position={[0, 0.829, -0.046]} rotation={[0, 0.476, 0]}>
                <primitive object={nodes.Hips} ref={boneRefs.Hips} name="Hips" position={[-0.001, 0.029, 0.033]} rotation={[-0.139, 0, 0]}>
                  <primitive object={nodes.Abdomen} ref={boneRefs.Abdomen} name="Abdomen" position={[0, 0.106, 0]} rotation={[0.096, 0, 0]}>
                    <primitive object={nodes.Torso} ref={boneRefs.Torso} name="Torso" position={[0, 0.162, 0]} rotation={[0.193, -0.475, 0.071]}>
                      <primitive object={nodes.Chest} ref={boneRefs.Chest} name="Chest" position={[0, 0.216, 0]} rotation={[0.007, 0, 0]}>
                        <primitive object={nodes.Neck} ref={boneRefs.Neck} name="Neck" position={[0, 0.133, 0]} rotation={[-0.019, 0, 0]}>
                          <primitive object={nodes.Head} ref={boneRefs.Head} name="Head" position={[0, 0.077, 0]} rotation={[-0.049, -0.001, 0]} />
                        </primitive>
                        <primitive object={nodes.ShoulderL} ref={boneRefs.ShoulderL} name="ShoulderL" position={[0.099, 0.029, 0.021]} rotation={[-2.664, -0.369, -2.056]}>
                          <primitive object={nodes.UpperArmL} ref={boneRefs.UpperArmL} name="UpperArmL" position={[0, 0.066, 0]} rotation={[-1.813, -0.136, 1.185]}>
                            <primitive object={nodes.LowerArmL} ref={boneRefs.LowerArmL} name="LowerArmL" position={[0, 0.182, 0]} rotation={[-0.25, -0.013, -0.375]}>
                              <primitive object={nodes.WristL} ref={boneRefs.WristL} name="WristL" position={[0, 0.235, 0]} rotation={[0.022, 0.036, 0.021]}>
                                <primitive object={nodes.Index1L} ref={boneRefs.Index1L} name="Index1L" position={[0, 0.028, 0]} rotation={[-0.015, 0.03, -0.187]}>
                                  <primitive object={nodes.Index2L} ref={boneRefs.Index2L} name="Index2L" position={[0, 0.124, 0]} rotation={[-0.077, -0.07, 0.132]}>
                                    <primitive object={nodes.Index3L} ref={boneRefs.Index3L} name="Index3L" position={[0, 0.033, 0]} rotation={[-0.159, 0.019, 0.052]}>
                                      <primitive object={nodes.Index4L} ref={boneRefs.Index4L} name="Index4L" position={[0, 0.03, 0]} rotation={[-0.06, 0.019, 0.011]} />
                                    </primitive>
                                  </primitive>
                                </primitive>
                                <primitive object={nodes.Middle1L} ref={boneRefs.Middle1L} name="Middle1L" position={[0, 0.028, 0]} rotation={[0.052, -0.038, 0.035]}>
                                  <primitive object={nodes.Middle2L} ref={boneRefs.Middle2L} name="Middle2L" position={[0, 0.124, 0]} rotation={[-0.189, 0.042, 0.085]}>
                                    <primitive object={nodes.Middle3L} ref={boneRefs.Middle3L} name="Middle3L" position={[0, 0.04, 0]} rotation={[-0.241, 0.017, -0.036]}>
                                      <primitive object={nodes.Middle4L} ref={boneRefs.Middle4L} name="Middle4L" position={[0, 0.04, 0]} rotation={[-0.038, 0.019, -0.022]} />
                                    </primitive>
                                  </primitive>
                                </primitive>
                                <primitive object={nodes.Ring1L} ref={boneRefs.Ring1L} name="Ring1L" position={[0, 0.028, 0]} rotation={[0.031, -0.098, 0.258]}>
                                  <primitive object={nodes.Ring2L} ref={boneRefs.Ring2L} name="Ring2L" position={[0, 0.123, 0]} rotation={[-0.158, 0.327, -0.048]}>
                                    <primitive object={nodes.Ring3L} ref={boneRefs.Ring3L} name="Ring3L" position={[0, 0.034, 0]} rotation={[-0.234, 0.09, -0.073]}>
                                      <primitive object={nodes.Ring4L} ref={boneRefs.Ring4L} name="Ring4L" position={[0, 0.033, 0]} rotation={[-0.15, 0.061, -0.01]} />
                                    </primitive>
                                  </primitive>
                                </primitive>
                                <primitive object={nodes.Pinky1L} ref={boneRefs.Pinky1L} name="Pinky1L" position={[0, 0.028, 0]} rotation={[0.066, -0.132, 0.462]}>
                                  <primitive object={nodes.Pinky2L} ref={boneRefs.Pinky2L} name="Pinky2L" position={[0, 0.119, 0]} rotation={[-0.248, 0.33, -0.091]}>
                                    <primitive object={nodes.Pinky3L} ref={boneRefs.Pinky3L} name="Pinky3L" position={[0, 0.027, 0]} rotation={[-0.185, -0.109, -0.056]}>
                                      <primitive object={nodes.Pinky4L} ref={boneRefs.Pinky4L} name="Pinky4L" position={[0, 0.028, 0]} rotation={[-0.235, -0.036, -0.01]} />
                                    </primitive>
                                  </primitive>
                                </primitive>
                                <primitive object={nodes.Thumb1L} ref={boneRefs.Thumb1L} name="Thumb1L" position={[0, 0.028, 0]} rotation={[0.156, 0.37, -0.75]}>
                                  <primitive object={nodes.Thumb2L} ref={boneRefs.Thumb2L} name="Thumb2L" position={[0, 0.082, 0]} rotation={[0.106, -0.236, 0.185]}>
                                    <primitive object={nodes.Thumb3L} ref={boneRefs.Thumb3L} name="Thumb3L" position={[0, 0.032, 0]} rotation={[-0.163, -0.132, 0.235]} />
                                  </primitive>
                                </primitive>
                              </primitive>
                            </primitive>
                          </primitive>
                        </primitive>
                        <primitive object={nodes.ShoulderR} ref={boneRefs.ShoulderR} name="ShoulderR" position={[-0.098, 0.029, 0.021]} rotation={[-2.664, 0.369, 2.056]}>
                          <primitive object={nodes.UpperArmR} ref={boneRefs.UpperArmR} name="UpperArmR" position={[0, 0.066, 0]} rotation={[-1.545, 0.205, -1.122]}>
                            <primitive object={nodes.LowerArmR} ref={boneRefs.LowerArmR} name="LowerArmR" position={[0, 0.182, 0]} rotation={[-0.285, -0.504, 0.615]}>
                              <primitive object={nodes.WristR} ref={boneRefs.WristR} name="WristR" position={[0, 0.235, 0]} rotation={[0.019, -0.043, -0.078]}>
                                <primitive object={nodes.Index1R} ref={boneRefs.Index1R} name="Index1R" position={[0, 0.028, 0]} rotation={[-0.015, -0.03, 0.187]}>
                                  <primitive object={nodes.Index2R} ref={boneRefs.Index2R} name="Index2R" position={[0, 0.124, 0]} rotation={[-0.101, 0.074, -0.13]}>
                                    <primitive object={nodes.Index3R} ref={boneRefs.Index3R} name="Index3R" position={[0, 0.033, 0]} rotation={[-0.178, -0.018, -0.051]}>
                                      <primitive object={nodes.Index4R} ref={boneRefs.Index4R} name="Index4R" position={[0, 0.03, 0]} rotation={[-0.06, -0.019, -0.011]} />
                                    </primitive>
                                  </primitive>
                                </primitive>
                                <primitive object={nodes.Middle1R} ref={boneRefs.Middle1R} name="Middle1R" position={[0, 0.028, 0]} rotation={[0.052, 0.038, -0.035]}>
                                  <primitive object={nodes.Middle2R} ref={boneRefs.Middle2R} name="Middle2R" position={[0, 0.124, 0]} rotation={[-0.205, -0.041, -0.048]}>
                                    <primitive object={nodes.Middle3R} ref={boneRefs.Middle3R} name="Middle3R" position={[0, 0.04, 0]} rotation={[-0.241, -0.017, 0.036]}>
                                      <primitive object={nodes.Middle4R} ref={boneRefs.Middle4R} name="Middle4R" position={[0, 0.04, 0]} rotation={[-0.038, -0.019, 0.022]} />
                                    </primitive>
                                  </primitive>
                                </primitive>
                                <primitive object={nodes.Ring1R} ref={boneRefs.Ring1R} name="Ring1R" position={[0, 0.028, 0]} rotation={[0.031, 0.098, -0.258]}>
                                  <primitive object={nodes.Ring2R} ref={boneRefs.Ring2R} name="Ring2R" position={[0, 0.123, 0]} rotation={[-0.158, -0.327, 0.048]}>
                                    <primitive object={nodes.Ring3R} ref={boneRefs.Ring3R} name="Ring3R" position={[0, 0.034, 0]} rotation={[-0.234, -0.09, 0.073]}>
                                      <primitive object={nodes.Ring4R} ref={boneRefs.Ring4R} name="Ring4R" position={[0, 0.033, 0]} rotation={[-0.15, -0.061, 0.01]} />
                                    </primitive>
                                  </primitive>
                                </primitive>
                                <primitive object={nodes.Pinky1R} ref={boneRefs.Pinky1R} name="Pinky1R" position={[0, 0.028, 0]} rotation={[0.066, 0.132, -0.462]}>
                                  <primitive object={nodes.Pinky2R} ref={boneRefs.Pinky2R} name="Pinky2R" position={[0, 0.119, 0]} rotation={[-0.202, -0.397, 0.293]}>
                                    <primitive object={nodes.Pinky3R} ref={boneRefs.Pinky3R} name="Pinky3R" position={[0, 0.027, 0]} rotation={[-0.185, 0.109, 0.056]}>
                                      <primitive object={nodes.Pinky4R} ref={boneRefs.Pinky4R} name="Pinky4R" position={[0, 0.028, 0]} rotation={[-0.235, 0.036, 0.01]} />
                                    </primitive>
                                  </primitive>
                                </primitive>
                                <primitive object={nodes.Thumb1R} ref={boneRefs.Thumb1R} name="Thumb1R" position={[0, 0.028, 0]} rotation={[0.208, -0.315, 0.951]}>
                                  <primitive object={nodes.Thumb2R} ref={boneRefs.Thumb2R} name="Thumb2R" position={[0, 0.082, 0]} rotation={[0.106, 0.236, -0.185]}>
                                    <primitive object={nodes.Thumb3R} ref={boneRefs.Thumb3R} name="Thumb3R" position={[0, 0.032, 0]} rotation={[-0.163, 0.132, -0.235]} />
                                  </primitive>
                                </primitive>
                              </primitive>
                            </primitive>
                          </primitive>
                        </primitive>
                      </primitive>
                    </primitive>
                  </primitive>
                </primitive>
                <primitive object={nodes.UpperLegL} ref={boneRefs.UpperLegL} name="UpperLegL" position={[0.12, 0.099, 0.018]} rotation={[0.215, -1.12, -2.722]}>
                  <primitive object={nodes.LowerLegL} ref={boneRefs.LowerLegL} name="LowerLegL" position={[0, 0.433, 0]} rotation={[Math.PI / 2, 1.036, -Math.PI / 2]} />
                </primitive>
                <primitive object={nodes.UpperLegR} ref={boneRefs.UpperLegR} name="UpperLegR" position={[-0.121, 0.099, 0.018]} rotation={[-0.041, 1.21, 2.756]}>
                  <primitive object={nodes.LowerLegR} ref={boneRefs.LowerLegR} name="LowerLegR" position={[0, 0.433, 0]} rotation={[Math.PI / 2, -1.092, Math.PI / 2]} />
                </primitive>
              </primitive>
              <primitive object={nodes.FootL} ref={boneRefs.FootL} name="FootL" position={[0.121, 0.023, -0.187]} rotation={[1.568, 0.005, -1.026]} />
              <primitive object={nodes.PTL} ref={boneRefs.PTL} name="PTL" position={[0.568, 0.627, 0.227]} rotation={[-0.005, 0, 0]} />
              <primitive object={nodes.FootR} ref={boneRefs.FootR} name="FootR" position={[-0.069, 0.023, 0.174]} rotation={[1.565, 0.001, -0.116]} />
              <primitive object={nodes.PTR} ref={boneRefs.PTR} name="PTR" position={[-0.018, 0.423, 0.659]} rotation={[-0.005, 0, 0]} />
            </primitive>
            <group name="Adventurer_Body">
              <skinnedMesh name="Cube063" geometry={nodes.Cube063.geometry} material={materials.Skin} skeleton={nodes.Cube063.skeleton} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
})

export default Model

useGLTF.preload('/assets/models/player/AdventurerArms.glb')
